### PR TITLE
Add data-hero to Psammead's amp-img

### PR DESCRIPTION
**Pull request by DarioR01**
Partial resolution of [#9801](https://github.com/bbc/simorgh/issues/9801)

Adds data-hero attribute to Psammead amp-img.

**Code changes:**

- adds data-hero to all amp-img in Psammead

---

- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)
- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]

**Review by pvaliani — APPROVED** [review]

**Comment by HarveyPeachey** [comment]
@DarioR01 Is this `data-hero` attribute being used correctly here? My understanding is that it should only be put on the most substantial image on the page so it loads that image first as that's what a user would be shown in the viewport. It looks like it's being applied to all images looking at the PR? Or have I missed something?

**Comment by DarioR01** [comment]
> ding is that it should only be put on the

My understanding is that data-hero is used for AMP Caches and AMP Optimizers to server-side render the image. Normally, as you suggested, this would only be implemented on the most important images ("hero images"). Since there is no list of images that are "most important" on our pages, and technically speaking there is nothing that does not allow me to place this in every single image, I assumed this should have been applied to every image.
I will double-check to be on the safe side.

**Comment by HarveyPeachey** [comment]
> My understanding is that data-hero is used for AMP Caches and AMP Optimizers to server-side render the image. 

Yeah from that explanation then, if it serverside renders all the images first as a priority, let's say on a PGL page with lots of images, the server will prioritise loading rendering those images first as they all have the `data-hero` attribute, which I suspect would increase the Total Blocking Time as the page won't be sent to the user until all those images have been loaded server-side, which may have a worse impact on the core web vitals score. It's best if you test to see if it makes a difference in the score as this is probably okay for assets where there are only a couple of images, but might be bad for pages with a lot of images.

**Comment by DarioR01** [comment]
You are right, I should have had data-hero only on the first image... oh well, time to revert

**Pull request merged**
