### PR TITLE
Remove Storybook Preview

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves [No Issue]

**Overall change:** _Removes storybook preview and husky._

**Code changes:**

- _Remove storybook preview - will require followup work to remove supporting infrastructure on AWS._
- _Remove Husky._

---

- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)
- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by HarveyPeachey** [comment]
Was there discussion somewhere about why these are being removed?

**Comment by andrewscfc** [comment]
> Was there discussion somewhere about why these are being removed?

The storybook preview action seems to be broken but we have the same thing already via Chromatic. We've decided to remove it on that basis rather than maintaining it.

I'm unsure why husky is being removed though? I'm not sure the issues we have in the Simorgh repo apply in Psammead?

**Comment by ryanmccombe** [comment]
We agreed to remove / strip back husky in a tech meeting - already done for Simorgh - https://github.com/bbc/simorgh/pull/9307

Psammead has the same issue - hooks take ages to run (especially pre-push) so people avoid them with `--no-verify`.

Can revert if people find these useful - would be surprising if people liked these though, given they disliked them in simorgh?

**Comment by HarveyPeachey** [comment]
> We agreed to remove / strip back husky in a tech meeting - already done for Simorgh - [bbc/simorgh#9307](https://github.com/bbc/simorgh/pull/9307)
> 
> Psammead has the same issue - hooks take ages to run (especially pre-push) so people avoid them with `--no-verify`.
> 
> Can revert if people find these useful - would be surprising if people liked these though, given they disliked them in simorgh?

I'm not sure about other devs experiences, but I've found the pre-push where it runs unit tests that have changed from the latest branch useful, and it has caught some issues with code before. The pre-commit I don't mind that stuff going, liniting could be useful however.

**Review by andrewscfc — APPROVED** [review]

**Review by HarveyPeachey — APPROVED** [review]

**Pull request merged**
