### PR TITLE
Amp validation allowfullscreen attribute

### LINKED ISSUE #4044: Live radio page fails AMP validation
**Describe the bug**
AMP validation is failing meaning the AMP pages will not be indexed by Google. 

**To Reproduce**

1. Go to https://www.bbc.com/korean/bbc_korean_radio/liveradio.amp
2. Validate using the [AMP validator extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc)
3. See error (as in screenshot)

**Expected behavior**
Fix the errors described in the screenshot. 

**Screenshots**
image

**Testing notes**
Using the extension detailed above ensure no errors are present on the PR. 

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ibMadbouly**
partially Resolves [#4044](https://github.com/bbc/simorgh/issues/4044) on simorgh

**Code changes:**

- in `packages/components/psammead-media-player/src/Amp/index.jsx` set the value of `allowfullscreen` attribute of `amp-iframe` to be a valid value `allowfullscreen` due to React making HTML attributes a boolean explicitly when passed in. https://github.com/bbc/psammead/blob/051d2e1213436683a13acbb05235bbbfa66300c8/packages/components/psammead-media-player/src/Amp/index.jsx#L24

- updated snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by DenisHdz — COMMENTED** [review]
Have you tried to use `allowFullScreen` in camelCase format?

**Comment by ibMadbouly** [comment]
@DenisHdz as atrribute value ?

**Comment by DenisHdz** [comment]
> @DenisHdz as atrribute value ?

Yep, just give it a go. Otherwise, looks good to do `allowfullscreen="allowfullscreen"`

```
<amp-iframe
     sandbox="allow-scripts allow-same-origin"
     layout="fill"
     frameborder="0"
     src={src}
     allowFullScreen
>
```

**Comment by ibMadbouly** [comment]
> allowFullScreen

tried it and it does not work

**Review by pjlee11 — APPROVED** [review]
LGTM 👍 

Tried this locally by updating the Simorgh node_modules to have the dist output with these changes and seeing the `allowfullscreen` validation error no longer present. 

image

**Review by DenisHdz — APPROVED** [review]
LGTM

**Review by dr3 — APPROVED** [review]

**Pull request merged**
