### PR TITLE
Update react-helmet

### PR DESCRIPTION
**Pull request by EinsteinNjoroge**
Part of  https://github.com/bbc/simorgh/issues/3893

**Overall change:** _Update react-helmet._

**Code changes:**

- _Update react-helmet._
---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by amywalkerdev — APPROVED** [review]
👍

**Review by DenisHdz — APPROVED** [review]

**Review by FK78 — APPROVED** [review]

**Review by Bopchy — COMMENTED** [review]
I pulled this branch and tried running the tests locally after an `npm ci:packages`. There still seem to be warnings coming from `packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx` and 
`packages/containers/psammead-timestamp-container/src/index.test.jsx`

**Comment by EinsteinNjoroge** [comment]
@Bopchy be sure to run `npm i` before running the tests since we're installing a newer version of the dependency

**Comment by EinsteinNjoroge** [comment]
> I pulled this branch and tried running the tests locally after an `npm ci:packages`. There still seem to be warnings coming from `packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx` and
> `packages/containers/psammead-timestamp-container/src/index.test.jsx`

@Bopchy Nice catch, it's should fixed now

**Comment by Bopchy** [comment]
Checked it out locally, and all the relevant warnings are now gone. Thanks for the changes!

**Review by Bopchy — APPROVED** [review]

**Comment by EinsteinNjoroge** [comment]
This PR does not require testing since it's a dependency update.

**Pull request merged**
