### PR TITLE
Updating react version

### LINKED ISSUE #389: Update React version to v16.8.6
**Is your feature request related to a problem? Please describe.**
We are currently using React 16.7.0, we should update our components to use 16.8.6.

**Describe the solution you'd like**
Update React versions for all packages that use React. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Regression testing with Storybook.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by chris-hinds**
Resolves #389 

**Overall change:** 
Updates react version to 16.8.6 (current latest) in all psammead packages

**Code changes:**

- Update version of react from 16.6.3 to 16.8.6 in package devDependancies

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by j-pendlebury** [comment]
Do we need to bump the version of each indivdual package? If not, I'm happy to approve this.

**Comment by chris-hinds** [comment]
> Do we need to bump the version of each individual package? If not, I'm happy to approve this.

After a couple of discussion we do not think we need to do this. So this is ready for CR.

**Review by j-pendlebury — APPROVED** [review]

**Review by rossgaskell — APPROVED** [review]
👍

**Comment by PriyaKR** [comment]
LGTM(regression on psammead looks good).

**Pull request merged**
