### PR TITLE
Use Eastern Arabic numerals in Jalaali dates

### LINKED ISSUE #2358: Implement numeral translator helper into psammead-calendars for Jalaali
**Is your feature request related to a problem? Please describe.**
Now that #2300 has been merged we need to implement the new numeral translator helper into the Jalaali alternative calendar found in `psammead-calendars` because at the moment it's using western Arabic numerals (1,2,3,4..).

**Describe the solution you'd like**
In the Jalaali calendar utility found in `psammead-calendars`, we need to use `makeNumeralTranslator()` from psammead locales to convert the western Arabic numerals produced by the Jalaali calendar into its eastern Arabic numeral equivalent.

We should compare output using the new helper with what is currently shown on live (using the old `postformat` implementation) and verify byte-for-byte that there is no difference

**Testing notes**
- Update unit tests/snapshots
- Verify that the output uses Eastern Arabic numerals and the characters display as expected

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jamesdonoh**
Resolves https://github.com/bbc/psammead/issues/2358

**Overall change:** _Uses the numerals in `psammead-locales` to ensure that Jalaali dates are formatted for Persian and Pashto using  Eastern Arabic numerals_

**Code changes:**

- Uses the numerals translator that was added in https://github.com/bbc/psammead/issues/2299
- Returns Eastern Arabic numerals in Jalaali date day and year components
- Update unit tests to expect Eastern Arabic numerals
- Use `import` instead of `require` for consistency

Demonstration using CLI:
```shell
$ node
> const moment = require('moment');
> const jalaali = require('./dist').jalaali;
> const persianNow = moment().locale('fa');
> jalaali.formatDate(persianNow);
'۱۷ مهر ۱۳۹۸'
```

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by RayNjeri — APPROVED** [review]

**Review by HarveyPeachey — DISMISSED** [review]
LGTM 👍

**Review by HarveyPeachey — COMMENTED** [review]
Woops just noticed that the [README.md](https://github.com/bbc/psammead/tree/latest/packages/utilities/psammead-calendars) will need updating with information about the numeral helper and the format example will need updating with the eastern Arabic numerals

**Comment by jamesdonoh** [comment]
Good idea @HarveyPeachey - have updated it.

**Review by HarveyPeachey — APPROVED** [review]
LGTM

**Review by oluoluoxenfree — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Pull request merged**
