### PR TITLE
Update Sitewide Links colours

### LINKED ISSUE #272: Update psammead-sitewide-links colours
**Is your feature request related to a problem? Please describe.**
UX have updated the design regarding the colours used in the footer component.

Depends on #277.

**Describe the solution you'd like**
The `psammead-sitewide-links` component should be updated to match the new styling:

- The background will now be `#222222`, or "Ebon", which is exposed in `psammead-styles` as `C_EBON`.
- The horizontal lines will now be `#3f3f42`, or "Shadow" ~, which should be added to `psammead-styles`.~ (Done in #277)
- Text colour will be altered in a future ticket.

**Testing notes**
WCAG colour ratio check, check with colour blindness filters. Check to make sure the colours are as expected. As this is Psammead, no Cypress tests will be required.

Dev insight: Unit test snapshots should be updated and component should reviewed in Storybook.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by sareh**
Resolves #272

**Overall change:** Update background colour to Ebon `#222222` and borders to Shadow `#3F3F42`.

Screenshot of Storybook, showing backgroundcolour change to Ebon in dev tools:
screen shot of sitewide links

Screenshot of Storybook dev tools, showing borders change to Shadow
screen shot sitewide links

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — DISMISSED** [review]

**Review by bcmn — DISMISSED** [review]
Checked in Storybook, looks good 🙂

**Comment by jamesbrumpton** [comment]
LGTM

**Comment by ChrisBAshton** [comment]
Blocked on #310 (we ideally want Storybook deployment to work before we merge new changes).

**Review by dr3 — APPROVED** [review]

**Comment by ChrisBAshton** [comment]
Ignoring error check, which is the example-button/package.json failing Snyk test.

Have now removed in Snyk so this should no longer be an issue in future.

Merging as already had 'mergeable' label from Test.

**Pull request merged**
