### PR TITLE
Fix grid css for Useful Links

### LINKED ISSUE #2311: Styling for grid - Useful Links
**Is your feature request related to a problem? Please describe.**
After talking to UX, there were some inconsistencies with the alignment of items in the grid (at a particular screen width).

**Describe the solution you'd like**
Align items to the top instead of the centre. Add column grid gap of 30px.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

- [x] This feature is expected to need manual testing.

**Expected alignment (to the top):**

Screenshot 2019-10-02 at 15 37 50

**Current alignment (centred):**

Screenshot 2019-10-02 at 15 50 02

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #2311 

**Overall change:** 
Changed grid items alignment and columns gap.
Changed order of elements displayed in columns (from _row by row_ to _column by column_) so that the screen reader announces them correctly.

**Code changes:**
Align items to the top instead of the centre. Add column grid gap of 30px.
Change grid to include rows amount so that the order of the elements is correct

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by DenisHdz — COMMENTED** [review]
Can't this work be done in the other on going [PR](https://github.com/bbc/psammead/pull/2308)? Otherwise, you will have to update CHANGELOG and bump the package in this PR  too.

**Comment by OlgaLyubin** [comment]
> Can't this work be done in the other on going [PR](https://github.com/bbc/psammead/pull/2308)? Otherwise you will have to wait until the other gets merged and then update CHANGELOG and bump the package in this PR again.

I can add it to the previous PR, however I guess it would need to be code reviewed again?

**Review by DenisHdz — COMMENTED** [review]
LGTM on the latest browsers, but are we expecting this separation on IE? 
ie11-separation

**Comment by OlgaLyubin** [comment]
**Internet Explorer now:**

Screenshot 2019-10-09 at 09 46 19

**Comment by OlgaLyubin** [comment]
There is currently an issue in IE that if the screen is very wide, one of the items flows over to the previous row. This issue only happens while using `column-count` in css instead of `min-width: 50%`. However, only the former actually splits the list in a correct order (the one set by accessibility requirements). 
Does anybody know if this could be fixed? I have tried just about everything already, but Internet Explorer keeps giving bugs.

Screenshot 2019-10-09 at 09 46 19

Screenshot 2019-10-09 at 09 46 34

**Comment by OlgaLyubin** [comment]
All fixed now. Thanks to @DenisHdz 

Screenshot 2019-10-09 at 11 10 30

**Review by DenisHdz — APPROVED** [review]
Great work 👍

**Review by j-pendlebury — APPROVED** [review]
Wooo! Looks great 👍

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
