### PR TITLE
Bumped jalaali-js

### PR DESCRIPTION
**Pull request by hotinglok**
Resolves #2002 
Missed bump when doing the others since it was nested (my b).

**Overall change:** 
Bumped dependency.

**Code changes:**
- Updated package.json
- Updated package-lock.json

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by thekp — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Comment by dr3** [comment]
Unit tests cover this :)

**Comment by jamesdonoh** [comment]
Why was this bumped?

**Comment by hotinglok** [comment]
> Why was this bumped?

@jamesdonoh Dependabot PR here: https://github.com/bbc/psammead/pull/2002. I didn't realise that I missed it when I did this PR: https://github.com/bbc/psammead/pull/2083

**Comment by jamesdonoh** [comment]
OK thanks @lokh01 :)

**Pull request merged**
