### PR TITLE
Bumping dependencies

### PR DESCRIPTION
**Pull request by FK78**
Resolves multiple dependabot PRs.

**Overall change:** _Bumping dependencies._

**Code changes:**

- _Bump @babel/cli ^7.10.4  →  ^7.10.5._
- _Bump @babel/core ^7.10.4  →  ^7.11.1._
- _Bump @babel/plugin-transform-runtime ^7.10.4  →  ^7.11.0._
- _Bump @babel/preset-env ^7.10.4  →  ^7.11.0._
- _Bump @loadable/component ^5.13.0  →  ^5.13.1._
- _Bump @testing-library/jest-dom ^5.11.0  →  ^5.11.3._
- _Bump @testing-library/react ^10.4.3  →  ^10.4.8._
- _Bump @testing-library/react-hooks ^3.3.0  →   ^3.4.1._
- _Bump babel-plugin-styled-components 1.10.7  →   1.11.1._
- _Bump browserslist ^4.12.2  →  ^4.14.0._
- _Bump jest ^26.1.0  →  ^26.4.0._
- _Bump ramda ^0.27.0  →  ^0.27.1._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by chewu — APPROVED** [review]

**Review by thekp — APPROVED** [review]

**Comment by staylos92** [comment]
LGTM 👍

**Review by RichardPK — APPROVED** [review]
👍

**Comment by chris-hinds** [comment]
CI is failing to install the packages with this error

```
npm ERR! lodash not accessible from @babel/helper-skip-transparent-expression-wrappers:@babel/types
```

**Review by RichardPK — COMMENTED** [review]
~👍~  👎

**Review by rhenshaw56 — APPROVED** [review]

**Pull request merged**
