### PR TITLE
removed unused package podcast-promo

### LINKED ISSUE #4554: Remove unused package podcast-promo
**Is your feature request related to a problem? Please describe.**
The podcast promo component in Psammead is not used as we ported it over to Simorgh. However, the package in Psammead still requires version bumps in order for CI to pass.

Podcast Promo: https://github.com/bbc/psammead/tree/latest/packages/components/psammead-podcast-promo

We should remove the package from Psammead following our deprecation guide: https://github.com/bbc/psammead/blob/latest/docs/Deprecating-a-Package.md

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by shikharvashistha**
Resolves #4554
**Overall change:** Removed package psammead-podcast-promo from project

**Code changes:** Removed psammead-podcast-promo package

- Followed the guidelines mentioned [here](https://github.com/bbc/psammead/blob/latest/docs/Deprecating-a-Package.md)

Greetings of the day,

I've removed the package psammead-podcast-promo. Please review the pr and let me know in case of any changes if required.

Thanks & Regards
Shikhar Vashistha
---

- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)
- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by rebeccamcginn** [comment]
Thank you, Shikhar! We'll get this reviewed tomorrow 😄

**Comment by shikharvashistha** [comment]
Why did you do that @DarioR01 ?

**Comment by shikharvashistha** [comment]
Greetings of the day @rebeccamcginn,

Please guide me how should I proceed. I'm confused.

Thanks & Regards
@shikharvashistha

**Comment by rebeccamcginn** [comment]
> Greetings of the day @rebeccamcginn,
> 
> Please guide me how should I proceed. I'm confused.
> 
> Thanks & Regards
> @shikharvashistha

Hello, Shikhar. My apologies; CI was failing due to a reference to psammead-podcast-promo in the yarn lock file. Unfortunately, when yarn.lock is deleted, we pull in minor package updates which results in pull requests with hundreds of files changed. In order to make the code review process easier, I created a PR to close the ticket without the yarn cache updates. We are reviewing our use of yarn cache with the goal to reduce the impact on the code review experience. I am sorry that we have not made use of this PR.

**Pull request closed without merging**
