### PR TITLE
Create story promo list component

### LINKED ISSUE #477: Create story promo list
An a11y criteria is to have story promos in a list when there is more than 1 item

**Describe the solution you'd like**
Create an unordered list and list item component with no styling except a separator line

```
import { unorderedList, listItem } from '@bbc/psammead-story-promo-list'
```
The list should have zero styling, padding or margins except for the separator line, which will be a border bottom. 

The separator shouldn't appear at the bottom of all list items or at the top.

UX spec for separator line:

- Height: 1px
- Colour: `C_LUNAR` from `@bbc/psammead-styles/colours`
- Spacing:
  - `0` - `600px`:
    - Above: 16px - `GEL_SPACING_DBL` from `@bbc/gel-foundations`
    - Below: 8px - `GEL_SPACING` from `@bbc/gel-foundations`
  - +`600px`:
    - Above: 16px - `GEL_SPACING_DBL` from `@bbc/gel-foundations`
    - Below: 16px - `GEL_SPACING_DBL` from `@bbc/gel-foundations`
  - +`1008px`:
    - Above: 24px - `GEL_SPACING_TRPL` from `@bbc/gel-foundations`
    - Below: 24px - `GEL_SPACING_TRPL` from `@bbc/gel-foundations`

Developer note, Role `list` and role `listitem` will need to be applied to the corresponding list items due to a VoiceOver bug to reinstate the list semantics

**Testing notes**
[Tester to complete]

Dev insight: Snapshots and storybook
Storybook should include multiple stories in a list, built up.
UX will provide information about the stories to show in storybook

**Additional context**
[Screenreader UX](https://docs.google.com/document/d/1dBN1hAL6VrXWnIEDgYyR_MJP6UgQFnW_KiqcTLUeGUU/edit#)

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #477

**Overall change:** 
Implement an unordered list and a list item component with no styling except a separator line to be used with `StoryPromos`.

**Code changes:**
- Create `StoryPromoUl` component
- Create `StoryPromoLi` component

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by dr3** [comment]
Blocked on package versioning decision

**Review by andrew-nowak — DISMISSED** [review]
lgtm :+1:

**Review by j-pendlebury — DISMISSED** [review]
Looks awesome 👍

**Review by andrew-nowak — APPROVED** [review]
nice catch; lgtm :+1:

**Review by j-pendlebury — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM. Happy for this to be merged.

**Pull request merged**
