### PR TITLE
psammead-image: Fix transparency issue

### LINKED ISSUE #6429: Images with transparencies show the placeholder through the transparent bits
**Is your feature request related to a problem? Please describe.**
If a journalist adds a PNG with transparency in it to a CPS STY, then Simorgh displays the image with the BBC blocks image placeholder visible through it (on both Canonical and AMP).

Screen Shot 2020-05-06 at 10 53 46

[Asset where the image above lives.](https://www.bbc.co.uk/news/uk-politics-49560557)

**Describe the solution you'd like**
If the image has a transparency, then the placeholder should not be visible, and the background should match the background of the page.

I suspect there will need to be some accessibility considerations around ensuring the background colour is correct in various reading modes.

**Describe alternatives you've considered**
N/A

**Testing notes**
- Create unit tests to check if placeholder present when a image is passed in.
- Alt test matches the image, rather than placeholder.
- Check colour matches the page background.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by 12**
Resolves bbc/simorgh#6429

How image placeholders work in Simorgh:
- An image component overlays a base64 SVG of the BBC blocks, and acts as a background.
- If an image is transparent, this SVG will be visible through the transparent parts, as the SVG does not get removed, simply overlaid. As shown below:

image

**Overall change:** 

- Add a background to the actual image element (the one that overlays the BBC blocks), when a `backgroundColour` prop is passed to the psammead image component. This will prevent the BBC blocks from being visible.
image

- When the image fails to load, for whatever reason, the alt text shows. Currently, this alt text is shown as if it were inside the placeholder (BBC blocks) SVG. To retain this UX, if there is an error with the image, the background colour is removed, resuming its original transparent behaviour, and appearing inside the placeholder.

**Code changes:**

- Add `backgroundColour` prop to image
- Add a `backgroundEnabled` state, that is set to `true` be default and disabled when `onerror` is triggered on the image.
- Add unit tests
- Add a new story to storybook to demonstrate this fix

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by greenc05** [comment]
Please could we check how this works in a custom high contrast mode in IE and when a user changes their colour preferences in FF? @HarveyPeachey might kindly be able to help out if you don't have access to a windows machine @12

**Review by ghost — APPROVED** [review]
Nicely done 👍

**Comment by 12** [comment]
Changes accepted by UX.

**Comment by simonsinclair** [comment]
Nice work, Rhys. I'm curious, did we ever try removing the blocks as opposed to concealing them?

**Comment by 12** [comment]
Interesting @simonsinclair, I had tried this before, but to no avail. Though I've just tried something a bit simpler and it appears to be working well.

**Review by mykeels — COMMENTED** [review]
What's supposed to happen when we change the background colour knob value on the transparent image story?

**Comment by 12** [comment]
Closing in favour of bbc/simorgh#6574

**Pull request closed without merging**
