### PR TITLE
 Remove alpha tag from Radio Schedules component

### LINKED ISSUE #2993: Remove alpha tag from Radio Schedules component
**Is your feature request related to a problem? Please describe.**
The Radio Schedules component will be an alpha component.

This component should be tested according to the a11y requirements to remove the tag.

**Describe the solution you'd like**
Remove alpha tag after successful a11y swarm on the component.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #2993

**Overall change:** 
After carried out an [Accessibility Swarm](https://github.com/bbc/simorgh/issues/5236) for the `RadioSchedules` component and fixed all the bugs, we can move forward and remove the alpha tag from the component.

**Code changes:**
- Remove `alpha` tag from the `package.json`
- Bump package to a stable version
- Remove alpha text from `README`

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by OlgaLyubin — COMMENTED** [review]
Version in `package.json` should be updated too

**Comment by DenisHdz** [comment]
> Version in `package.json` should be updated too

Thought I did 🙈

**Review by OlgaLyubin — COMMENTED** [review]
Could you please update this Readme section too?

Screenshot 2020-04-08 at 12 47 08

**Review by OlgaLyubin — APPROVED** [review]
Looks good 🎉 👍

**Review by Bopchy — APPROVED** [review]
LGTM 🎉

**Pull request merged**
