### PR TITLE
Remove alpha tag from section label

### LINKED ISSUE #615: Section Label - Remove alpha tag
**Is your feature request related to a problem? Please describe.**
Remove alpha from the `Section Label`.

**Describe the solution you'd like**
- Remove `alpha` tag from the `package.json`
- Bump package to a stable version
- Remove alpha text from `README`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Resolves #615

**Overall change:** 
After carried out an [Accessibility Swarm](https://github.com/bbc/psammead/issues/558) for the `Section Label` component and fixed in [this](https://github.com/bbc/psammead/pull/611) PR the issues found in [Windows High Contrast mode](https://github.com/bbc/psammead/issues/605), we can move forward and remove the alpha tag from the component.

Remove alpha tag from `SectionLabel`
**Code changes:**

- Remove alpha tag from `SectionLabel`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by DenisHdz — CHANGES_REQUESTED** [review]
We also need to remove it from [here](https://github.com/bbc/psammead/blob/05bb1f005a072ea0b6abb89f70c6bd26be85d8d1/packages/components/psammead-section-label/package.json#L40)

**Review by DenisHdz — APPROVED** [review]
LGTM 👍

**Review by dr3 — APPROVED** [review]
LGTM, before merge can you please add some description to the PR about why youre making it not alpha please :) (that you did a swarm, how you did it, what devices etc)

**Comment by david-boydell** [comment]
Hi @sadickisaac,

We have amended line 53 in the Usage section (_without a horizontal bar_) so that the props were separated by line breaks, we haven't done this for the example above it though. Before I put this as RFM can you let me know if this is expected?

Cheers
David

**Comment by ghost** [comment]
@david-boydell This is due to `prettier` formatting. The first example was formatted well and therefore  no reformatting was needed.

**Comment by david-boydell** [comment]
Cool, thanks @sadickisaac, this is rfm.

**Pull request merged**
