### PR TITLE
Override numerals in moment - Gujarati

### LINKED ISSUE #2106: Override numerals in moment - Gujarati
**Is your feature request related to a problem? Please describe.**
Gujarati service has incorrect timestamp numerals

**Describe the solution you'd like**
Override moment locale `gu-in` to have the correct numeral format.

Expected `14 જુલાઈ 2019`, what we currently have `૮ જુલાઈ ૨૦૧૯`

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #2106 

**Overall change:** 
Override moment numerals for locale `gu` (Gujarati) with western numerals.

**Code changes:**
Added `gu.js` to `psammead_locale` to override moment locale numerals.
Added tests for `gu`.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by AlistairGempf — APPROVED** [review]
Looks good

**Review by DenisHdz — APPROVED** [review]
LGTM 👍

**Review by ghost — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Review by sareh — APPROVED** [review]

**Comment by staylos92** [comment]
LGTM 👍

**Pull request merged**
