### PR TITLE
Talos - Bump @bbc/gel-foundations

### PR DESCRIPTION
**Pull request by bbc-news-frameworks**
👋 The following packages have been updated:

@bbc/psammead

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-bulletin

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-copyright

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-bulleted-list

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-caption

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-consent-banner

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-brand

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-navigation

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-paragraph

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-story-promo

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-radio-schedule

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-byline

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-sitewide-links

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-script-link

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-useful-links

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-most-read

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-timestamp

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-section-label

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-media-indicator

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-figure

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-play-button

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-grid

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-story-promo-list

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-embed-error

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-headings

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-storybook-helpers

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

@bbc/psammead-timestamp-container

<details>
<summary>Details</summary>
@bbc/gel-foundations  ^3.4.3  →  ^4.0.0

| Version | Description |
|---------|-------------|
| 4.0.0 | [PR#3128](https://github.com/bbc/psammead/pull/3128) Update `GEL_GROUP_4_SCREEN_WIDTH_MAX` value |
</details>

### CODE REVIEW

**Comment by sareh** [comment]
Testing this PR - the only change made to the underlying package is to update the `GEL_GROUP_4_SCREEN_WIDTH_MAX` value. This value is used in packages:
```
psammead-grid
psammead-most-read
psammead-sitewide-links
psammead-story-promo
```
We should test these manually to ensure we are not introducing any regressions.

**Comment by sareh** [comment]
**psammead-story-promo**

Note, this PR fixes the issue with StoryPromo 'top story' variant

Screenshot 2020-02-13 at 11 33 39

Compare with this, which looks broken:
https://bbc.github.io/psammead/iframe.html?id=components-storypromo-storypromo--top-story-promo-index-alsos-multiple



**psammead-most-read**

Screenshot 2020-02-13 at 11 30 37

**psammead-sitewide-links**

Screenshot 2020-02-13 at 11 29 28
Screenshot 2020-02-13 at 11 28 58

**psammead-grid**
Screenshot 2020-02-13 at 11 41 35
Note that the Psammead Grid story that using Story Promo will only show the 'fixed' story promo in the next round of Talos which will pull in this updated Story Promo version.

**Review by AlistairGempf — APPROVED** [review]
All looks good to me

**Review by DenisHdz — APPROVED** [review]
Thanks for checking these regressions 👍

**Pull request merged**
