### PR TITLE
Copyright Lang attribute

### LINKED ISSUE #623: Visually displayed copyright text requires lang attribute
**Is your feature request related to a problem? Please describe.**
The visually displayed copyright text is always in English 

**Describe the solution you'd like**
* On non-English articles we should add a `lang` attribute to the visually displayed copyright text so this can be announced by screen readers with the correct accent. This should not be applied to the visually hidden text 'Image source, '.
* In Persian we expect the copyright span to be right aligned.

Arises from https://github.com/bbc/simorgh/pull/618

**Testing notes**
English News article example: http://localhost:7080/news/articles/cn7769kpk9mo
Persian article example: http://localhost:7080/persian/articles/cyddjz5058wo

* Screen reader - test both the visually hidden text such as: 'Image source, ' and the visually displayed copyright text such as 'Getty images' are read with the correct accents - Make sure to check that this works ok with `role="text"`
* Check to make sure that the visually hidden text 'Image source, ' (translated) is read with a Farsi accent on `Persian`
* Check to make sure that the visually displayed copyright text such as 'Getty images' is read with an English accent on `Persian`

Dev insight: We should have unit tests for the changes.

### PR DESCRIPTION
**Pull request by RayNjeri**
Resolves [#623](https://github.com/bbc/simorgh/issues/623)

**Overall change:** _Add default "en-gb" lang attribute to copyright_

**Code changes:**

- _Add default lang attribute to copyright regardless of the page's service._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by twinlensreflex — DISMISSED** [review]
👍 looks good to me!

**Review by 12 — DISMISSED** [review]
This LGTM, assuming we don't mind it appearing on English articles as well. The original issue explicitly states
>On non-English articles

I can't see this being an issue though.

**Comment by greenc05** [comment]
@RayNjeri Looking at this I think we have applied the lang attribute to the wrapping paragraph? Is that useful? We should make sure we are only applying the lang attribute when the content is in a different language e.g. On Persian, 'Image source, ' will be translated to Persian, and 'Getty images' will be english...

**Comment by RayNjeri** [comment]
@greenc05 I was informed that currently, we don’t specify the language of the copyright, hence screenreaders will assume it’s the same language as the containing page, therefore, the need to add the default lang-attribute

**Comment by greenc05** [comment]
@RayNjeri I don't think the requirement in the Issue has been documented correctly, just going to check with @jimjohnsonrollings

**Comment by sareh** [comment]
@RayNjeri I think this Psammead PR shouldn't be necessary - that the work to address the issue can be carried out purely in Simorgh. 

In Simorgh, in the Copyright Container, we can check what the service's lang attribute is from the ServiceContext.
Only if lang is not `en-GB`, we can add `lang="en-GB"` to the Copyright component and add `lang={lang}` to the VisuallyHiddenText component. 
https://github.com/bbc/simorgh/blob/bb2bbc0a09d8f1901857159762d49d8dc6e5ec84/src/app/containers/Copyright/index.jsx#L8

**Comment by RayNjeri** [comment]
@sareh i will close this PR

**Pull request closed without merging**
