### PR TITLE
Talos - Catchup on talos work

### PR DESCRIPTION
**Pull request by bbc-news-frameworks**
👋 The following packages have been published:
@bbc/psammead-amp-geo
@bbc/psammead-brand
@bbc/psammead-caption
@bbc/psammead-consent-banner
@bbc/psammead-copyright
@bbc/psammead-figure
@bbc/psammead-headings
@bbc/psammead-image-placeholder
@bbc/psammead-image
@bbc/psammead-inline-link
@bbc/psammead-media-indicator
@bbc/psammead-media-player
@bbc/psammead-navigation
@bbc/psammead-paragraph
@bbc/psammead-section-label
@bbc/psammead-sitewide-links
@bbc/psammead-story-promo-list
@bbc/psammead-story-promo
@bbc/psammead-timestamp
@bbc/psammead-visually-hidden-text
@bbc/psammead-timestamp-container
@bbc/gel-foundations
@bbc/moment-timezone-include
@bbc/psammead-assets
@bbc/psammead-locales
@bbc/psammead-storybook-helpers
@bbc/psammead-styles
@bbc/psammead-test-helpers

So we need to bump them in the following packages:
psammead
@bbc/psammead-headings
@bbc/psammead-story-promo
@bbc/psammead-timestamp
@bbc/psammead-storybook-helpers
@bbc/psammead-section-label
@bbc/psammead-media-indicator
@bbc/psammead-caption
@bbc/psammead-timestamp-container
@bbc/psammead-navigation
@bbc/psammead-story-promo-list
@bbc/psammead-consent-banner
@bbc/psammead-sitewide-links
@bbc/psammead-inline-link
@bbc/psammead-figure
@bbc/psammead-copyright
@bbc/psammead-brand
@bbc/psammead-paragraph
@bbc/psammead-image-placeholder

### CODE REVIEW

**Review by dr3 — APPROVED** [review]
LGTM, will require minor testing in storybook

**Review by thekp — APPROVED** [review]

**Comment by staylos92** [comment]
LGTM 👍

**Comment by staylos92** [comment]
The font size seems to have increased on the story promo list, See https://www.chromaticqa.com/snapshot?appId=5d28eb5ee163f6002046d6fb&id=5d66918173567a002033864e

**Comment by staylos92** [comment]
The above is covered by https://github.com/bbc/psammead/pull/1930

**Pull request merged**
