### PR TITLE
A11y storybook addon

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves N/A

**Overall change:** 
Adds A11y add-on to Storybook.

image

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by greenc05** [comment]
Thanks for adding this @jblaut 

Please could we configure this with the following tags?

wcag2a | WCAG 2.0 Level A
wcag2aa | WCAG 2.0 Level AA
wcag21aa | WCAG 2.1 Level AA

https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#api-name-axeconfigure

**Comment by j-pendlebury** [comment]
@greenc05 do you mean only run checks against those tags, or make sure they're included among the others?

**Comment by greenc05** [comment]
@jblaut I think we should retrieve only those rules/run those checks, if that's possible? e.g. we aren't concerned with 'section508' or 'experimental' https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#user-content-example-1

**Comment by j-pendlebury** [comment]
@greenc05 yup, it is possible 😄 was just double checking

**Review by 12 — CHANGES_REQUESTED** [review]
Looks good, but can you investigate the failure with Snyk?

**Comment by j-pendlebury** [comment]
@rhell the failure is due to one of the main dependencies (axe-core) uses the MPL-2.0 license

image

**Review by DenisHdz — DISMISSED** [review]

**Review by 12 — DISMISSED** [review]
clap

**Comment by david-boydell** [comment]
LGTM, RFM

**Comment by jamesdonoh** [comment]
We may not be able to use this add-on because according to some sources its licence (MPL 2.0) is not compatible with our OSS project licences. I'm attempting to get clarification from the wider BBC community.

**Comment by j-pendlebury** [comment]
waiting to find out what happens with Snyk and the license issue

**Comment by jamesdonoh** [comment]
The licence issue should now have been resolved so this is unblocked @jblaut

**Review by amywalkerdev — APPROVED** [review]
👍

**Review by DenisHdz — APPROVED** [review]
👍

**Comment by david-boydell** [comment]
Nothing has changed, this is RFM

**Pull request merged**
