### PR TITLE
New inline link styling

### LINKED ISSUE #397: Inline link hover styling overlaps when the user is zoomed in
**Describe the bug**
If the user zooms in and hovers over an inline link the styling appears to overlap

**To Reproduce**

1. Run Storybook
2. Select Caption with an inline link
3. Using the browser's zoom in function, zoom in
4. Hover over the inline link
5. Observe

**Expected behavior**
The inline link styles should not overlapped when zoomed in
Screen Shot 2019-03-26 at 15 09 13

- [ ] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

### LINKED ISSUE #716: New inline link styling
**Is your feature request related to a problem? Please describe.**
There has been a long drawn out saga with the inline link styling and this aims to finally resolve it. UX would like the inline link to have a red background when hover & focused. The new Reith font (https://github.com/bbc/psammead/pull/548) allows for this styling. 

**Describe the solution you'd like**
Update `psammead-inline-link` to use background colour when hovered/focused. Ensure all accessibility best practices are still maintained, such as: 
- visual change that is not colour dependent and can be seen in all high-contrast 
- legibility of each line is maintained (EG: not cluttered and easily read by some dyslexic)
- when zooming the browser legibility is maintained
- when setting browser font-size to large legibility is maintained 
- all connected colours meet the colour contrast ratio 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshot test should cover the new styling, no cypress tests are needed, a detailed visual and accessibility regression of the various world service scripts should be performed

**Additional context**
Previous related issues: 
- https://github.com/bbc/simorgh/issues/828
- https://github.com/bbc/simorgh/issues/863
- https://github.com/bbc/psammead/issues/397
- https://github.com/bbc/simorgh/issues/616
- https://github.com/bbc/psammead/issues/222
- https://github.com/bbc/simorgh/issues/1055

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #397
Resolves #716

**Overall change:** Adds the new UX inline link styling which is a background colour on hover. Also maintains the border changing from 1px to 2px on hover for users in high constrast modes.

**Code changes:**

- On hover/focus the background becomes red and the text becomes white
- On hover/focus adds `pre-wrap` so that for links that wrap to new lines the letter on the end of the line has a slight background buffer
- Maintains a 2px border on hover/focus so there is a visual state change on high contrast modes
- On hover/focus adds minus margin and padding to increase the background for buffer between the end of the background colour and the actual letter (see screenshots with and without in comments)

Testing notes:

This is most easily tested by following the instructions on https://github.com/bbc/psammead/pull/719 and then testing as described in the notes below. Happy to pair with test on this work. 

- Open storybook and regression test the new inline link styling using the caption and paragraph stories that contain inline links, make sure to check different world services with varying scripts and line-heights. NB: The reason we should not use the inline-link story for this regression is that it does not set it's own typography styling as it's expected to be used as a child of another component
- Check firefox high contrast mode (Go to FireFox -> Preference -> Language & Appearance -> Colours -> 'Override the colours ...' set as Always)
- Check Windows high contrast mode
- Check with page zoomed to high percentages (300%+)
- Check across different breakpoints
- Check across different browsers
- Check #397 is fixed as part of this
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by pjlee11** [comment]
Without minus margin and padding

image

With minus margin and padding

image

Without minus margin & padding (Italic)

image

With minus margin & padding (italic)

image

Showing how the padding is affecting the element's background (Italic)

image

**Review by oluoluoxenfree — APPROVED** [review]

**Comment by pjlee11** [comment]
Going to move this back to "PR in progress" and update the paragraph and caption stories to give a realistically storybook example of the inline link

**Comment by pjlee11** [comment]
Firefox high contrast mode
firefox highcontrast mode

**Review by RayNjeri — APPROVED** [review]
Tested it out in high contrast mode. Everything seems to be work as expected.
LGTM!

**Review by j-pendlebury — APPROVED** [review]

**Pull request merged**
