### PR TITLE
Fix padding and margin on outer grid

### LINKED ISSUE #2780: First grid item is indented on IE
**Describe the bug**
The first grid item is indented on IE

**To Reproduce**

1. Go to https://bbc.github.io/psammead/?path=/story/components-grid--normal-slice-layout-for-1-or-5-items on IE 11
2. See error.

**Expected behavior**
The first grid item should not have extra spacing at the begin of the page.

**Screenshots**
Screenshot 1

**Desktop (please complete the following information):**

- OS: Windows
- Browser: IE
- Version: 11

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Part of https://github.com/bbc/simorgh/pull/4493
Resolves #2780, #2781

**Overall change:** _Fix first grid item identantation on IE._

**Code changes:**

- _Apply `display: inline-block` to the outerGrid. `display: inline` doesn't respect the padding and margins._
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by EinsteinNjoroge** [comment]
Screenshots
Screen Shot 2019-12-09 at 12 58 47 PM
Screen Shot 2019-12-09 at 12 57 38 PM

**Comment by DenisHdz** [comment]
> Screenshots
> Screen Shot 2019-12-09 at 12 58 47 PM
> Screen Shot 2019-12-09 at 12 57 38 PM

As you can see in the second screenshot, the top story image is not aligned with the second story below. You might try to fix it in this PR or open another issue to deal with that.

**Comment by EinsteinNjoroge** [comment]
@DenisHdz [this](https://github.com/bbc/psammead/pull/2796#issuecomment-563158438) difference only showed after fixing the initial indentation issue, we intend to fix it as a [separate issue](https://github.com/bbc/psammead/issues/2800) once this PR is merged.

**Review by thekp — APPROVED** [review]
👍

**Review by RayNjeri — APPROVED** [review]
LGTM

**Review by j-pendlebury — APPROVED** [review]

**Pull request merged**
