### PR TITLE
Remove unused GEL Types

### LINKED ISSUE #516: Remove unused GEL Types
**Is your feature request related to a problem?**
Following the discussion on [#465](https://github.com/bbc/psammead/issues/465), we decided to remove the large GEL Types sizes as UX are not currently planning to use any of these styles.

**Describe the solution you'd like**
Remove `Atlas`, `Elephant`, `Imperial`, `Royal`, `Foolscap` functions from `typography.js` and values from the `latin-and-cyrillic.js` script.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests will be sufficient

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #516

**Overall change:** 
Remove the GEL Types sizes for larger contexts.

**Code changes:**
- Remove `Atlas`, `Elephant`, `Imperial`, `Royal`, `Foolscap` values from `latin-and-cyrillic.js` script.
- Remove `getAtlas`, `getElephant`, `getImperial`, `getRoyal` and `getFoolscap` from `typography.js`
---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
LGTM

**Review by j-pendlebury — DISMISSED** [review]

**Review by dr3 — COMMENTED** [review]
Is this not a breaking change as its not backwards compatible?

**Comment by ghost** [comment]
Interesting, If the functions are not being used anywhere on the codebase, does it still make it a breaking change.

**Comment by dr3** [comment]
Yeah @sadickisaac, as its a public npm package which could be used by anyone

**Comment by david-boydell** [comment]
Did a quick regression and it all looks fine

**Comment by DenisHdz** [comment]
@dr3 Are you suggesting to increment the version to `2.0.0` instead of `1.3.0`?

**Comment by ghost** [comment]
@DenisBBC yeah, you should increment the version number.

**Review by ghost — APPROVED** [review]

**Review by j-pendlebury — APPROVED** [review]

**Comment by david-boydell** [comment]
Still looks good, rfm.

**Pull request merged**
