### PR TITLE
Fix frontpages amp img not showing in IE

### LINKED ISSUE #1931: AMP Images dont render in Story Promo without Grid
**Describe the bug**
When on devices without grid, like IE11, AMP images dont render. This is likely because the psammead placeholder div doesn't hold its own shape, meaning AMP doesnt think its visible, so doesnt render the image.

This doesnt happen on canonical because the image takes its own space. It does however mean image placeholders never show without grid.

**Describe the solution you'd like**
Fix it

**Testing notes**
[Tester to complete]

image

Dev insight: Snaps and manual

**Additional context**

### PR DESCRIPTION
**Pull request by EinsteinNjoroge**
Resolves https://github.com/bbc/simorgh/issues/1931

**Overall change:** _Fix story promo image widths for browsers without grid _

**Code changes:**

- _Replace `max-width` with `width` in story promo_
- _Set topstory width to `100%` for browsers without grid_

**Testing notes:**
Requires full visual regression on 
- Chrome, firefox (latest), IE 11 & 10
- AMP & Canonical on all above browsers
- 240px -> 1280px on all above browsers

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — CHANGES_REQUESTED** [review]
Top story AMP still doesn't show the image
image

**Review by j-pendlebury — APPROVED** [review]
image

Looks good 👍

**Review by dr3 — APPROVED** [review]
LGTM, great work

**Comment by dr3** [comment]
Added testing notes above, needs full regression of story promo on grid & non grid, amp & canonical

I tested locally by
1) Psammead - checkout branch
2) Psammead - `npm run ci:packages && npm run build`
3) Simorgh - checkout latest
4) Simorgh - npm ci
5) Simorgh - `cp -r ../psammead/packages/components/psammead-story-promo/dist/ ./node_modules/@bbc/psammead-story-promo/dist`
6) Simorgh - `npm run build && npm start`
7) Visit `http://localhost:7080/igbo.amp`

**Comment by david-boydell** [comment]
Looks good. Ready for merge.

**Pull request merged**
