### PR TITLE
Storybook update

### LINKED ISSUE #422: Update Storybook Version
**Is your feature request related to a problem? Please describe.**
We are using Storybook version `5.0.1`, which has a bug in the `addon-knobs` that overwrites text.

**Describe the solution you'd like**
We should update to at least version `5.0.2` which fixes this bug, but ideally the latest stable release which is `5.0.6`

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by amywalkerdev**
Resolves #422

**Overall change:**
Storybook has been updated to version 5.0.6
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by j-pendlebury** [comment]
Do we bump the version of Psammead when all that's changed is a dependency? Otherwise all good.

**Comment by amywalkerdev** [comment]
> Do we bump the version of Psammead when all that's changed is a dependency? Otherwise all good.

We didn't the last two times that Storybook was updated

**Review by j-pendlebury — DISMISSED** [review]

**Review by dr3 — CHANGES_REQUESTED** [review]
Need to update the top level changelog and bump

**Review by sareh — DISMISSED** [review]
👍 Looks good locally.

**Review by j-pendlebury — DISMISSED** [review]

**Review by dr3 — DISMISSED** [review]

**Review by dr3 — APPROVED** [review]

**Review by pjlee11 — APPROVED** [review]
LGTM

**Comment by jamesbrumpton** [comment]
LGTM. Happy for this to be merged.

**Pull request merged**
