### PR TITLE
Apply font style based on service: Navigation

### PR DESCRIPTION
**Pull request by ghost**
Contribute to #543

**Overall change:** Apply font style based on `service`
**Code changes:**

- Add required `service` prop on `Navigation` and `NavigationLi`
- Update `psammead-styles` to version `1.1.0` and `storybook-helpers` to `3.1.0`
- Update stories and tests.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by andrew-nowak — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Comment by david-boydell** [comment]
Hi @sadickisaac,

~We seem to have an issue with /news and /persian on Opera (Version:62). The text with either ReithSans or Nassim does not appear. If I remove either font from the styles using dev tools the text will reappear.~

image

~Might be worth mentioning it seems ok on Opera mini.~

**Comment by ghost** [comment]
@david-boydell Looking into that.

**Comment by david-boydell** [comment]
Hi @ sadickisaac, apologies for spotting this late. The issue seems to affect all components, not just this one.

**Comment by david-boydell** [comment]
The above comment from myself was an issue with Opera's VPN. This is ready for merge.

**Pull request merged**
