### PR TITLE
Update Storybook version plus other dependecies

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves N/A

**Overall change:** 
Updates versions of outdated dependencies, including version of Storybook.

**Code changes:**
Dependencies bumped:
* "@storybook/theming": "^5.1.8"
* "styled-components": "^4.3.1"
* "@storybook/addon-a11y": "^5.1.8"
* "@storybook/addon-actions": "^5.1.8"
* "@storybook/addon-notes": "^5.1.8"
* "@storybook/addon-viewport": "^5.1.8"
* "@storybook/react": "^5.1.8"
* "eslint-plugin-import": "^2.17.3"
* "lerna": "^3.15.0"
* "prettier": "^1.18.2"
* "stylelint-processor-styled-components": "^1.8.0"

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by j-pendlebury** [comment]
the latest versions of `addon-knobs` (checked version 5.1.2 and above) causes issues with Storybook and inputProvider where the values are not being updated, e.g. Headline component doesn't change text from the default English value to any of the translations when interacting with the "Select a language" drop down.

**Comment by j-pendlebury** [comment]
bumping to version of `addon-knobs` to 5.1.0 and higher, introduces a bug with our inputProvider. More info here: https://github.com/bbc/psammead/pull/594#issuecomment-501702562

**Review by pjlee11 — APPROVED** [review]
LGTM 👍

**Comment by sareh** [comment]
The Storybook functionality looks good. 
There's this console error that is not on `latest` but is on this branch:
Screen Shot 2019-06-14 at 12 57 37

**Comment by dr3** [comment]
Popping back in progress due to https://github.com/bbc/psammead/pull/631#issuecomment-502084020

**Comment by j-pendlebury** [comment]
@sareh this was flagged on #594 as well, see: https://github.com/bbc/psammead/pull/594#pullrequestreview-248109348

**Review by sareh — APPROVED** [review]
Thanks for updating to the latest version of storybook. I don't see those console errors any longer. 🎉

**Review by dr3 — APPROVED** [review]

**Comment by staylos92** [comment]
LGTM 👍  performed regression testing against latest and all looks good.

**Pull request merged**
