### PR TITLE
Move typography to use rem instead of em for font size

### PR DESCRIPTION
**Pull request by dr3**
Resolves https://github.com/bbc/psammead/issues/289

Updates typography to use rem over em

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by bcmn — APPROVED** [review]
Looks good when locally linked into Simorgh.

**Review by bcmn — CHANGES_REQUESTED** [review]
Jenkins is failing because our `npm run ci:packages` includes `--force-local`. This should not happen `--force-local` should be a developer convenience, & we should avoid doing it on CI, which we want to  reflect user journeys as realistically as possible.

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/psammead/pull/295

**Comment by dr3** [comment]
Blocked on https://github.com/bbc/psammead/pull/295

**Review by pjlee11 — APPROVED** [review]

**Review by bcmn — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
👍

**Pull request merged**
