### PR TITLE
Remove `fill` in SVGs

### LINKED ISSUE #699: Remove fills in psammead-assets SVGS
**Is your feature request related to a problem? Please describe.**
The current WS psammead assets, [found here](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-assets/src/svgs.jsx) have fill & stroke values like `fill="#fff"` and `stroke="#FFF"`

This is causing SVGs to be white when CSS is disabled, making them invisible.

**Describe the solution you'd like**
Remove all white fills and strokes in the SVGS, allowing them to default to black, which we currently override with white in CSS. With the exception for the pipe/line that goes between BBC News and the service name, looking at the Igbo SVG as an example, it would appear that his element within the SVGs will need to keep ```stroke="#FFF"```.

image

**Testing notes**
[Tester to complete]

Dev insight: No automated, existing covers. Turning off CSS should show SVG in black.

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves #699

**Overall change:** Remove `fill` from our SVGs in `psammead-assets`, so that they can still be seen with no CSS

**Code changes:**

- Remove `fill` in SVGs
- Replace `stroke` value from `#fff` to `#000`, and add inline styles

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by j-pendlebury** [comment]
###  * With stroke set to `#FFF` and CSS
image

### * With stroke set to `#FFF` and no CSS
image

----
----

### * With no stroke set and CSS
image

### * With no stroke set and no CSS
4A38BE4B-0BCD-4212-9DA9-B8C085E641F8

----
----

### * With stroke set to `stroke="#000" style={{"stroke": "#fff"}}` and CSS
9FAE68C1-64F9-4AB4-ADB7-384F30628840

### * With stroke set to `stroke="#000" style={{"stroke": "#fff"}}` and no CSS
45188377-C7C4-43F8-88CD-16CB65A038EB

**Review by dr3 — APPROVED** [review]

**Review by DenisHdz — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
Could we remove `style={"stroke": "#fff"}` from the svgs
See https://js-cuavax.stackblitz.io

**Review by ghost — APPROVED** [review]
Double checked locally. Looks great didn't see the [comment above](https://github.com/bbc/psammead/pull/704#issuecomment-505413134)

**Comment by david-boydell** [comment]
Looks good. Ready for merge.

**Pull request merged**
