### PR TITLE
Update section label to use border

### LINKED ISSUE #605: section label: set colour using border
outcome of #558 
**Is your feature request related to a problem? Please describe.**
In Windows High Contrast mode, the line in the section label disappears. Instead of using a background colour, we should set the colour of this element using a `border`.

**Describe the solution you'd like**
`` `border-top: ${1/16}rem solid ${C_PEBBLE};` ``
remove `height` and `background`.
Only set border-top (or border-bottom) to avoid doubling the height of the line

Users of HCM may be using a grey as their background colour, so in HCM we should use a safer colour; use the following example for inspiration

```css
@media screen and (-ms-high-contrast: active) {
  border-color: windowText;
}
```

**Describe alternatives you've considered**

**Testing notes**
The following accessibility testing should be done: points 4, 5, 6, & 7 under 'Checklist manual' on https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Resolves #605

**Overall change:** Update the `SectionLabel` implementation to use `border-top` instead of `background` and `height`.

**Code changes:**

- Update section label css to use `border-top`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]
Nice one 👍

**Review by dr3 — APPROVED** [review]

**Review by 12 — APPROVED** [review]
LGTM

**Comment by greenc05** [comment]
The following accessibility testing should be done as part of this PR if it hasn't already: points 4, 5, 6, & 7 under 'Checklist manual' on https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers

**Comment by DenisHdz** [comment]
Just went through the checklist with @aacn500 and everything looks fine 👍 

IMG_7958
IMG_7957
IMG_7959

**Comment by jamesbrumpton** [comment]
Happy for this to be merged.

**Pull request merged**
