### PR TITLE
Use new GEL spacing constants

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #NUMBER

**Overall change:** 
Use new GEL spacing constants added in this [PR](https://github.com/bbc/psammead/pull/2947) across all Psammead packages. 

I also took the opportunity to replace some `rem` values with existing GEL constants.

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by Bopchy — APPROVED** [review]
Noticed this use of `2.5rem` [here](https://github.com/bbc/psammead/blob/0f377554ec25ed47d0ad047e5c27c49eaedd3ae0/packages/components/psammead-headings/src/index.jsx#L21), `1rem` [here](https://github.com/bbc/psammead/blob/0f377554ec25ed47d0ad047e5c27c49eaedd3ae0/packages/components/psammead-script-link/src/index.stories.jsx#L11) and [here](https://github.com/bbc/psammead/blob/0f377554ec25ed47d0ad047e5c27c49eaedd3ae0/packages/utilities/psammead-assets/src/svgs.stories.jsx#L20). Otherwise looks good to me.

**Comment by DenisHdz** [comment]
> Noticed this use of `2.5rem` [here](https://github.com/bbc/psammead/blob/0f377554ec25ed47d0ad047e5c27c49eaedd3ae0/packages/components/psammead-headings/src/index.jsx#L21), `1rem` [here](https://github.com/bbc/psammead/blob/0f377554ec25ed47d0ad047e5c27c49eaedd3ae0/packages/components/psammead-script-link/src/index.stories.jsx#L11) and [here](https://github.com/bbc/psammead/blob/0f377554ec25ed47d0ad047e5c27c49eaedd3ae0/packages/utilities/psammead-assets/src/svgs.stories.jsx#L20). Otherwise looks good to me.

Thanks for double checking. I've also updated those 👍

**Review by AlistairGempf — APPROVED** [review]
Looks good 👍

**Comment by RichardPK** [comment]
Rad. This was on my to do list, nice one. 

I need to do something similar for Simorgh - there are a few instances of hard-coded REMs now covered by the new consts

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
