### PR TITLE
Storybook stories cleanup

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves N/A

**Overall change:** 
Group stories into categories since we're adding utilities and containers to our storybook and it's getting a bit messy.

**Code changes:**
- `[NAME]|` creates a category
- `[NAME]/` creates a folder

image

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by 12 — DISMISSED** [review]
This is a good idea. Genuine question (and from what I haven't found online, the answer is probably no), can we automatically generate the hierarchy based on the folder structure?

**Comment by j-pendlebury** [comment]
@rhell I don't really have an answer for you. I only saw this was possible from looking at another company's storybook, and didn't find anything about organising stories within Storybook docs 🤷‍♀

**Review by DenisHdz — APPROVED** [review]
Great job 👍

**Review by andrew-nowak — APPROVED** [review]
heck yeah

**Comment by david-boydell** [comment]
Looks good, this is ready for merge.

**Pull request merged**
