### PR TITLE
Fix summary visibility for breakpoints below 1008px

### PR DESCRIPTION
**Pull request by ghost**
Resolves #NUMBER

**Overall change:** Fix summary visibility for breakpoints below 1007px
As per Zeplin documentation:
0-599 has summary
600-1007 hide summary [due to height of component]
1008+ has summary

**Code changes:**

- Add min-width and max-width to summary media query
- Update snapshots.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by Bopchy — APPROVED** [review]
Looks good 👍

**Review by AlistairGempf — APPROVED** [review]
Looks good to me

**Review by ryanmccombe — APPROVED** [review]

**Review by j-pendlebury — APPROVED** [review]

**Comment by PriyaKR** [comment]
Storypromo in psammead storybook seems to have summary above 600px and below 600px it doesn't have summary which is not same as expected from this PR.

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
