### PR TITLE
Apply font based on service: MediaIndicator

### PR DESCRIPTION
**Pull request by ghost**
Contributes to #543 

**Overall change:** Apply font style based on the `service`
**Code changes:**

- Add required `service` prop
- Update `psammead-styles` to version `1.1.0`
- Update stories and tests

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by j-pendlebury — APPROVED** [review]
Looks good ⭐️

**Review by j-pendlebury — APPROVED** [review]
Looks good ⭐️

**Comment by j-pendlebury** [comment]
Apparently I really liked it so I approved it twice 🤷‍♀

**Review by andrew-nowak — APPROVED** [review]

**Comment by david-boydell** [comment]
Looks good.

**Pull request merged**
