### PR TITLE
Simplifies stories

### LINKED ISSUE #2157: Stop building complex stories in psammead packages
**Is your feature request related to a problem? Please describe.**
In psammead we have a number of stories, like [story promo](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/index.stories.jsx) where we setup extremely complicated story designs.

This is just mimicking the layout in simorgh, IMO we should keep stories for psammead as simple as possible, just highlighting the bare bones components. Adding `VisuallyHiddenText`, `MediaIndicator` & `Timestamp` to the story of `Story Promo` gives a false representation of what the `story promo` component provides. 

**Describe the solution you'd like**
Slim down our existing stories, isolating them to only contain what they export. We should discuss if we should rely on Simorgh or a seperate collection of stories, to give a representation of what you _can_ build with psammead.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by samora**
Resolves #2157 

**Overall change:** Simplifies stories. Remove dependencies which are not important to demonstrating usage.

**Code changes:**

- Remove story promo's dependency on `Timestamp`. 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by sareh — COMMENTED** [review]
Looks good. Please also update the version in the package.json, package-lock.json and Changelog. A patch version increase would be good.

**Review by thekp — APPROVED** [review]

**Review by pharingee — APPROVED** [review]
LGTM

**Review by sareh — APPROVED** [review]
👍 Looks great!

**Review by dr3 — APPROVED** [review]

**Review by FK78 — APPROVED** [review]
LGTM.

**Pull request merged**
