### PR TITLE
Override moment numerals - Hindi

### LINKED ISSUE #2105: Override moment numerals - Hindi
**Is your feature request related to a problem? Please describe.**
Hindi service has incorrect timestamp numerals. i.e 

**Describe the solution you'd like**
Override moment locale `hi` to have the correct numeral format.

Expected `14 जुलाई 2019`, what we currently have `८ जुलाई २०१९`

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Resolves #2105 

**Overall change:** Override moment numerals for locale `hi` (Hindi)

**Code changes:**

- Add `hi` to override default moment numerals
- Update tests

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by AlistairGempf — APPROVED** [review]
👍

**Comment by AlistairGempf** [comment]
Looks like there's a failing test due to a timeout, not sure it's related to these changes.

**Comment by AlistairGempf** [comment]
Other services that have been overridden have a story in `psammead-locales/moment/index.stories.jsx`. I'm not sure if this one needs one or not.

**Comment by ghost** [comment]
It needs story in storybook as well 👍 Adding that.

**Comment by ghost** [comment]
> Looks like there's a failing test due to a timeout, not sure it's related to these changes.

Not Related.

**Review by Bopchy — APPROVED** [review]

**Review by EinsteinNjoroge — APPROVED** [review]
LGTM

**Comment by staylos92** [comment]
LGTM 👍

**Review by dr3 — APPROVED** [review]

**Pull request merged**
