### PR TITLE
Update fallback text colour in Social Embed

### LINKED ISSUE #3488: Update fallback text colour in Social Embed
### Is your feature request related to a problem? Please describe.
Following UX review, we should update the text colour in the Social Embed fallback/Notice.

### Describe the solution you'd like
All standard text within the social embed notice component (not the link) should be `#3F3F42` (SHADOW).
Note: The current link colour is correct.

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- ~~[ ] This feature is expected to need manual testing.~~
- [x] This feature is expected to have a UX review.

### Additional context
https://bbc.github.io/psammead/?path=/story/components-socialembed-canonical--unsupported-provider - See storybook for what this currently looks like.

### PR DESCRIPTION
**Pull request by FK78**
Resolves #3488

**Overall change:** _Update fallback text colour in the Social Embed component._

**Code changes:**

- _Change colour from `C_EBON` to `C_SHADOW`._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by simonsinclair — APPROVED** [review]

**Review by Simon2828 — APPROVED** [review]
LGTM 👍

**Comment by FK78** [comment]
Approved in UX Review ✅

**Comment by paruchurisilpa** [comment]
Looks good to me..

**Pull request merged**
