### PR TITLE
RTL testing

### LINKED ISSUE #328: Investigate how we add RTL/LTR Support to components
**Is your feature request related to a problem? Please describe.**
We need to be able to test how components react to LTR/RTL text direction.

**Describe the solution you'd like**
We want to install Storybook Addon RTL to toggle the text direction per component.

**Describe alternatives you've considered**
N/A

**Testing notes**
N/A

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc
N/A

**Additional context**
https://github.com/unindented/storybook-addon-rtl

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves #328

**Overall change:**
We (the WS team) need to make sure that the current components will work with RTL left scripts. This is the beginning of such work.

**Code changes:**

- Added the `direction` CSS property to the component. The value of "RTL" can be passed via a prop, or if not, it will default to "LTR".
- A new story was added to reflect this change and to show an example of a RTL script. The caption was taken from an existing article on BBC Persian.
- Updated snapshots accordingly

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by dr3** [comment]
Just being nosey 🙈 Direction is usually done at the page level once, rather than the component level, perhaps we could try something like https://www.npmjs.com/package/storybook-addon-rtl? Saves each component being polluted by prop :)

**Comment by j-pendlebury** [comment]
@dr3 you're right, and I suggested doing it that way (even had a PR almost ready with the add-on config'ed), but was told to do it this way. We're still in a investigation phase so I guess we're looking at the best way of doing things. Thanks for your input though 😄

**Comment by chris-hinds** [comment]
I had suggested we look at passing a prop to the component for textDirection incase there was any other layout work we needed to do with the individual components and this way you would easily be able to test each component in isolation and see how they handle rtl.

But thinking about it I don't really think this is a genuine use case right now, and we can probably handle this by just setting  `dir="rtl"` in the parent as Jamie and Drew suggested. So ignore my initial thoughts :P

**Comment by chris-hinds** [comment]
One other thing to note is that the storybook addon places the `dir` attribute on the body tag however W3C states that this should be placed on the HTML tag. Just something to note when we actually implement this.

image

https://www.w3.org/International/questions/qa-html-dir#quickanswer

**Comment by dr3** [comment]
Sounds good @hindsc52, should custom direction logic be needed in future we can discuss possible wrappers or _direction_ context passing at that point :P 

On the `body` vs `head` comment, I imagine it's fine for our storybook use case, but we could push for https://github.com/unindented/storybook-addon-rtl/issues/2 to be addressed/fork if its not?

**Comment by chris-hinds** [comment]
> Sounds good @hindsc52, should custom direction logic be needed in future we can discuss possible wrappers or _direction_ context passing at that point :P
> 
> On the `body` vs `head` comment, I imagine it's fine for our storybook use case, but we could push for [unindented/storybook-addon-rtl#2](https://github.com/unindented/storybook-addon-rtl/issues/2) to be addressed/fork if it's not?

@dr3 agree! And yes for Storybook its fine, just a good reminder to make sure we place the attribute in the right place in the applications :)

And yes, we can comment again on that issue asking for it to be implemented.

**Comment by dr3** [comment]
> One other thing to note is that the storybook addon places the `dir` attribute on the body tag however W3C states that this should be placed on the HTML tag. Just something to note when we actually implement this.

This has now been resolved by https://github.com/unindented/storybook-addon-rtl/pull/5 and published as 0.2.0 :)

Also ~0.3.0 will be coming out soon to support SB5~ v0.2.2 now supports SB5 🎉

**Comment by j-pendlebury** [comment]
Closing this PR as we're going with #336 instead 🎉

**Pull request closed without merging**
