### PR TITLE
[amp-validation] Expand omit list for episode-list-image

### PR DESCRIPTION
**Pull request by ryanmccombe**
Related to: https://github.com/bbc/simorgh/issues/8590

**Overall change:** _Expand the omit list for props to be passed through to the img component_

**Code changes:**

- _Add additional fields to the omit list._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by SetJackal — APPROVED** [review]

**Comment by jroebu14** [comment]
How does that change img to amp-img? Also, do you think the image should be a responsive image? 768x432 seems quite large for an image that is e.g. 70x63 on an iphone X

**Comment by jroebu14** [comment]
should we be using this for the amp-img? https://github.com/bbc/psammead/tree/latest/packages/components/psammead-image

**Comment by ryanmccombe** [comment]
> How does that change img to amp-img?

That can be done in Simorgh - https://github.com/bbc/simorgh/pull/8607/files

That still results in amp validation errors though because we're passing the context props through to `amp-img` which is another validation error.  This PR is just to fix that second error

**Comment by ryanmccombe** [comment]
> Also, do you think the image should be a responsive image?

I think so - probably an unnecessary complexity for a psammead story though?

Could be done for the actual implementation in Simorgh - looks like the ARES response has `$recipe` tokens for these images eg `ichef.bbci.co.uk/images/ic/$recipe/p08b22y1.png`

**Review by rebeccamcginn — APPROVED** [review]

**Review by jroebu14 — APPROVED** [review]

**Pull request merged**
