### PR TITLE
Remove extra margin in story promo on desktop

### LINKED ISSUE #1086: Story promo component has 0.5rem margin bottom on desktop widths
**Describe the bug**
On any of the front pages, when in desktop width, the first story has 0.5rem margin-bottom applied to the image. This is only used when the first story is used as top story promo on mobile and should be removed from desktop widths.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.stage.bbc.co.uk/yoruba on a desktop device
2. Look at the first story
3. The image will have more padding between the story and the divider than other stories on the page

**Expected behaviour**

**Screenshots**
First story:
image

Second story:
image

**Additional context**

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves #1086 

**Overall change:** Remove margin-bottom on desktop devices for 1st story promo

**Code changes:**
- Change `margin-bottom: none` to `margin-bottom: 0`

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~~Tests added for new features~~
- [ ] Test engineer approval

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Bopchy** [comment]
Just wondering, how can I see this change locally?

**Review by andrew-nowak — APPROVED** [review]
looks good but needs a code owner approval

**Comment by ghost** [comment]
@Bopchy the change is in `storybook -> story promo -> top story` change the `ImageGrid` bottom style to `none` and then hover on the image.

**Review by dr3 — APPROVED** [review]

**Comment by david-boydell** [comment]
Looks good, this is ready for merge.

**Review by jamesbhobbs — CHANGES_REQUESTED** [review]
Temporarily blocking merge

**Review by jamesbhobbs — APPROVED** [review]

**Pull request merged**
