### PR TITLE
Attempt to fix talos

### PR DESCRIPTION
**Pull request by amywalkerdev**
**Overall change:** Talos has started failing since the 30th March. Maybe this will fix it? Who knows. What is the -a for? Answers on a postcard.

**Code changes:**

- Removing the -a option from the commands in the upgradeDependencies script.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by amywalkerdev** [comment]
Running the old command locally gives:
error: unknown option '-a'

**Review by j-pendlebury — APPROVED** [review]
Looks good, no idea why the `-a` flag was there in the first place, there's no mention of it on [`npm-check-updates` README](https://github.com/tjunnone/npm-check-updates), or its history 🤷‍♀

**Comment by DenisHdz** [comment]
> Looks good, no idea why the `-a` flag was there in the first place, there's no mention of it on [`npm-check-updates` README](https://github.com/tjunnone/npm-check-updates), or its history 🤷‍♀

Do we know what that `-a` flag generally does?

**Comment by thekp** [comment]
I went digging into their old commits and found this one: https://github.com/tjunnone/npm-check-updates/blob/950e666cc40735bb8e0a8e07b2c1409b72374b43/README.md#advanced-options

image

**Review by FK78 — APPROVED** [review]

**Comment by amywalkerdev** [comment]
> I went digging into their old commits and found this one: https://github.com/tjunnone/npm-check-updates/blob/950e666cc40735bb8e0a8e07b2c1409b72374b43/README.md#advanced-options
> 
> image

Thanks Khoa, I can't see another option that seems similar? I guess they totally dropped support for that

**Comment by FK78** [comment]
Support for `-a` was dropped in this PR: https://github.com/tjunnone/npm-check-updates/pull/483

**Pull request merged**
