### PR TITLE
Add fonts and UX colours needed for V1

### LINKED ISSUE #277: Update psammead-styles to reflect updated UX colours & fonts
**Is your feature request related to a problem? Please describe.**
UX have changed the colours utilised by the article. `psammead-styles` should reflect these new values & their names.

**Describe the solution you'd like**
All new UX colours are exported from `psammead-styles/colours`. These are:
- Shadow: `#3F3F42`
- Cloud-dark: `#757575`
- Cloud-light: `#BABABA`
- Lunar: `#F2F2F2`
- Ghost: `#FDFDFD`
- White: `#FFFFFF`

All UX-required font families are exported from `psammead-styles/fonts`. These are:
- Reith Serif Medium
- Reith Serif Medium Italic
- Reith Sans Regular
- Reith Sans Regular Italic
- Reith Sans Bold
- Reith Serif Light (n.b. Only in Most read, subset of numerals only, may not be visible in V1)

We should keep the colours that are no longer used in `psammead-styles` for now. 

We're adding more functionality, so a minor version bump should be used. Note: since we're still sub-1.0, this counts as a 'major' version, so consuming components need to have their package.json dependency versions updated. 

**Describe alternatives you've considered**

**Testing notes**
Happy to not write Cypress tests that test Psammead specifically. Will revisit this once it has been integrated with Simorgh.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by bcmn**
Resolves #277

**Overall change:** Introduces fonts & UX-defined colours required for V1.0.

**Code Changes:**
- Adds the required colours & fonts for the Simorgh 1.0 designs.
- Does not remove or deprecate previous colours.

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests ~added~ updated for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by sareh — APPROVED** [review]
👍 Looks great!

**Review by ChrisBAshton — APPROVED** [review]
Good stuff, Ben 👍

**Comment by bcmn** [comment]
Ngan Thi has reviewed the colour changes & given it the green light.

**Comment by jamesbrumpton** [comment]
Happy for this to be merged.

**Pull request merged**
