### PR TITLE
Set AMP Nav initial state

### PR DESCRIPTION
**Pull request by tochwill**
Resolves #NUMBER

**Overall change:** AMP initial state needs to be JSON, but in the nav it was being sanitised. This stops that from happening, so the state can be set correctly.

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by ghost** [comment]
CI is failing due to un bumped `package-lock.json`

**Comment by AlistairGempf** [comment]
Needs a `npm install` in the `psammead-navigation` folder to update the package-lock.json, looks good otherwise (other than the GitHub diff freaking out :D).

**Review by AlistairGempf — APPROVED** [review]

**Review by j-pendlebury — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by tochwill** [comment]
I'm going to merge this into Alistair's PR (https://github.com/bbc/psammead/pull/2771) and close this PR, to avoid 3 lots of conflicting version bumps

**Pull request closed without merging**
