### PR TITLE
Make timestamp :metal:

### LINKED ISSUE #566: Update Timestamp colour
**Is your feature request related to a problem? Please describe.**
`Timestamp` colour needs to be updated.

**Describe the solution you'd like**
Replace Timestamp colour from `C_CLOUD_DARK #757575` to `C_METAL #6e6e73`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by andrew-nowak**
Resolves #566 

**Overall change:** Our implementation of timestamp was using C_CLOUD_DARK, it should use C_METAL

**Code changes:**

- It now uses C_METAL :metal:

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]

**Comment by dr3** [comment]
Are we 100% sure we want this for both ws frontpages and articles?

**Comment by DenisHdz** [comment]
> Are we 100% sure we want this for both ws frontpages and articles?

💯
Screenshot 2019-06-05 at 15 13 05

**Review by dr3 — APPROVED** [review]
Ok, In guess articles timestamp in zeplin is out of date, LGTM

**Comment by jamesbrumpton** [comment]
LGTM. Happy for this to be merged.

**Pull request merged**
