### PR TITLE
Update gradient on Scrollable Navigation for > 400px

### LINKED ISSUE #3052: Navigation: Gradient on Scrollable Navigation is wrong width > 400px
**Describe the bug**
The gradient should be gradient `6em` above 400px page width - it currently remains at `3em`.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any page containing the navigation

**Expected behaviour**
The gradient should be gradient `6em` above 400px page width. Use the correct constants from Psammead to achieve this.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #3052

**Overall change:** 
Updated gradient to be 6rem on breakpoints above 400px.

**Code changes:**
- Updated gradient width
- Passed `isOpen` prop to one of the tests to remove the warning `Failed prop type: The prop isOpen is marked as required in CanonicalDropdown, but its value is undefined.`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by j-pendlebury — APPROVED** [review]
LGTM

**Review by DenisHdz — APPROVED** [review]
LGTM

**Comment by PriyaKR** [comment]
@OlgaLyubin is the gradient changes applied only to canonical?I can't see the changes on AMP.

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
