### PR TITLE
Create Optimo Base service

### LINKED ISSUE #3808: Create an Optimo Base service
**Is your feature request related to a problem? Please describe.**
We need to use the Sans Serif font family instead of Serif which is currently the default for latin languages.

**Describe the solution you'd like**
We want to add a Optimo Base Service to allow us to use the Sans Serif font family for our components.

**Describe alternatives you've considered**
We investigated not using Psammead components and instead creating our own components from scratch.  

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc
As this is a new service there should be no impact.

- [ ] This feature is expected to need manual testing.
No

### PR DESCRIPTION
**Pull request by rossgaskell**
Resolves #3808

**Overall change:** Adds Base service for Optimo Renditions

**Code changes:**

- Inherits from Latin Reith font styles but excludes Reith Serif

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by simonsinclair — APPROVED** [review]
🎉

**Review by chris-hinds — APPROVED** [review]

**Review by DenisHdz — COMMENTED** [review]
@rossgaskell Looks good, just needs to bump the `package.json`, `package-lock.json` and update the CHANGELOG for these packages.

**Comment by chris-hinds** [comment]
@rossgaskell we also have some issues with running forks against our internal Jenkins setup. I'll ensure you have right access to this repo, could you make sure branch/PR is created within the main Psammead repo so that the Jenkins pipeline will run.

We need to find a reliable way for having our pipeline run against forks.

**Comment by rossgaskell** [comment]
> @rossgaskell Looks good, just needs to bump the `package.json`, `package-lock.json` and update the CHANGELOG for these packages.

Is there an automated way of doing this @DenisHdz or is it a manual process?

**Comment by rossgaskell** [comment]
> @rossgaskell we also have some issues with running forks against our internal Jenkins setup. I'll ensure you have right access to this repo, could you make sure branch/PR is created within the main Psammead repo so that the Jenkins pipeline will run.
> 
> We need to find a reliable way for having our pipeline run against forks.

No worries @chris-hinds, will do

**Comment by DenisHdz** [comment]
> > @rossgaskell Looks good, just needs to bump the `package.json`, `package-lock.json` and update the CHANGELOG for these packages.
> 
> Is there an automated way of doing this @DenisHdz or is it a manual process?

Unfortunately not, you have to change the package version and add a new record to the log manually.

**Pull request merged**
