### PR TITLE
Fix for AV caption indentation on mobile

### LINKED ISSUE #4735: AV captions are indented on mobile
**Describe the bug**
AV captions are indented on mobile. They should be aligned with the edge of the media player as per the designs.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo on mobile
2. Scroll down to any media asset with a caption
4. See that the caption is indented and not aligned with the media player, H1/H2, or body text

**Expected behaviour**
The caption should not be indented. It should be aligned with the media player and other content blocks, as per the design:
image

**Screenshots**

image

**Smartphone (please complete the following information):**

- Device: Pixel 2
- OS: Android 10
- Browsers: Facebook for Android, Chrome v.78, Opera Mini, Firefox for Android

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by RayNjeri**
Signed-off-by: RayNjeri <rachael.njeri@andela.com>

Resolves https://github.com/bbc/simorgh/issues/4735

**Overall change:** _Fixes caption styling by removing extra padding for group 3 & 4 screen sizes._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by HarveyPeachey — COMMENTED** [review]
I don't think this change is necessary? It should be fine when we remove the indentation of the media player from this issue: https://github.com/bbc/simorgh/issues/4311. Because in the designs there is still padding for the captions because the video player and the caption are still in the same container.

**Comment by RayNjeri** [comment]
> I don't think this change is necessary? It should be fine when we remove the indentation of the media player from this issue: [bbc/simorgh#4311](https://github.com/bbc/simorgh/issues/4311). Because in the designs there is still padding for the captions because the video player and the caption are still in the same container.

Will the captions still be aligned with the rest of the text/paragraphs in the Page? Cz that was the whole essence, of this issue, Having the captions aligned with the media player, H1/H2, or body text

**Comment by HarveyPeachey** [comment]
> > I don't think this change is necessary? It should be fine when we remove the indentation of the media player from this issue: [bbc/simorgh#4311](https://github.com/bbc/simorgh/issues/4311). Because in the designs there is still padding for the captions because the video player and the caption are still in the same container.
> 
> Will the captions still be aligned with the rest of the text/paragraphs in the Page? Cz that was the whole essence, of this issue, Having the captions aligned with the media player, H1/H2, or body text

Yeah once the padding around the player is removed then the captions align fine:
Screenshot 2019-12-10 at 12 03 22

**Comment by RayNjeri** [comment]
Closing this in favor of the work done by @HarveyPeachey in https://github.com/bbc/simorgh/issues/4311.

**Pull request closed without merging**
