### PR TITLE
Media Indicator - Pass script

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #NUMBER

**Overall change:** 
Pass script to Media Indicator to apply the right typography.

**Code changes:**
- Pass `script` prop to the `MediaIndicator` component
- Update stories
- Update tests

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by sareh — APPROVED** [review]
👍 Thanks for this fix. When looking locally in Storybook, I see the script-specific font-size and line-height applied.

e.g. http://localhost:8180/?path=/story/components-mediaindicator-video--video-with-duration
Screenshot Media indicator with duration text

**Review by thekp — COMMENTED** [review]
https://github.com/bbc/psammead/pull/3075/files#diff-9caff7f606acc564ecc5cea4ea7173e6R37-R41

in this example ^ should we add an example of importing scripts and passing it as a prop, since it is a required prop?

**Comment by DenisHdz** [comment]
> https://github.com/bbc/psammead/pull/3075/files#diff-9caff7f606acc564ecc5cea4ea7173e6R37-R41
> 
> in this example ^ should we add an example of importing scripts and passing it as a prop, since it is a required prop?

Done :)

**Review by thekp — APPROVED** [review]

**Pull request merged**
