### PR TITLE
Add ability to limit service options

### LINKED ISSUE #757: Allow restricting inputProvider services
**Is your feature request related to a problem? Please describe.**
Currently the input provider provides all 40-something services. This isn't ideal as you cant use it to toggle variants of a component as you may not have all the config (e.g. footer) or assets (.e.g svgs)

**Describe the solution you'd like**
Add a 3rd argument to `inputProvider()` which is an array of services. It should then filter out unwanted services from its drop down.

**Testing notes**
[Tester to complete]

Dev insight: Test in storybook, a story will have a restricted list of services to pick.

**Additional context**

### PR DESCRIPTION
**Pull request by dr3**
Resolves #757

**Overall change:** Add ability to limit service options in input provider

**Code changes:**

- Allowed passing in an array of services to limit to

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~[ ] Tests added for new features~
- [ ] Test engineer approval

### CODE REVIEW

**Comment by dr3** [comment]
Ive noticed it says 'language' in the provider still (even though we previously changed from 'english' to 'news', moving to using services), ive raised https://github.com/bbc/psammead/issues/759 to update this to 'services'

**Comment by ghost** [comment]
Should this also be done to `dirDecorator` in this PR or should we open another issue? Same for addition of tests.

**Review by j-pendlebury — APPROVED** [review]

**Review by pjlee11 — APPROVED** [review]

**Review by DenisHdz — APPROVED** [review]

**Review by ghost — DISMISSED** [review]
https://github.com/bbc/psammead/pull/758#issuecomment-507979301

**Comment by dr3** [comment]
Chatted with @sadickisaac on slack, gunna write an issue https://github.com/bbc/psammead/issues/770 to allow limiting the Dir decorator per service. Just added some more tests for the input provider

**Review by thekp — CHANGES_REQUESTED** [review]
https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-storybook-helpers/README.md#exports

🙅‍♂ The readme needs updating

**Review by thekp — APPROVED** [review]
👍

**Comment by dr3** [comment]
No testing needed, will fix forward any issues, limited scope due to being storybook helper and unit tests pass

**Pull request merged**
