### PR TITLE
Moment locale deprecation warning

### LINKED ISSUE #3043: Moment deprecation warning
**Describe the bug**

```
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
```

**To Reproduce**

1. run `npm i && npm run dev`

**Expected behavior**
Doesnt throw this warning

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves https://github.com/bbc/simorgh/issues/3043

**Overall change:** Update Timestamp Container to remove Moment `defineLocale` deprecation warning in Simorgh

**Code changes:**

- In `timestampUtilities.js`, update the default locale from `en-GB` to `en-gb`, because Moment doesn't like capitals - fix for Simorgh
- Update Timestamp Container story to add all the missing locales

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~~Automated jest tests added (for new features) or updated (for existing features)~~
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by j-pendlebury** [comment]
There are two issues here that need fixing.
1. In Simorgh, when running locally, you can see the deprecation warning in the terminal. 
2. In Psammead, when running Storybook, the same warning can be seen in the console.

Issue number 1 seems to be fixed by the change in the first commit. We were setting the default locale as `en-GB` but the locale names are case sensitive and as far as Moment was aware, `en-GB` does not exist. Why it was giving us a deprecation warning for this? I have no clue.

Issue number 2, I'm still investigating, but it seems like Moment thinks that the locales we're defining are already defined.

So the warning seems to originate from [here](https://github.com/moment/moment/blob/13a61b285c095bda7ea8e33156090ea5ccfeaef1/moment.js#L1892-L1898), and it looks like the locales we added, e.g. `ig` or `pcm`, are included in the `locales` object, which makes Moment think that the locales we're adding already exist and it's complaining:
image
`console.log(locales)` ⬆️

I tried "fixing" this by using `updateLocale` instead of `defineLocale`, but then our unit tests fail:
image

**Comment by j-pendlebury** [comment]
err.. no idea what happened but I can no longer see the error in Psammead in Storybook

**Comment by dr3** [comment]
@jblaut could you ever see it in psammead? I thought this is a simorgh problem 🙈

**Comment by j-pendlebury** [comment]
@dr3 yeah I can still see it in Psammead. Forgot to remove the comment. So I got rid of the changes in https://github.com/bbc/psammead/pull/2240/commits/689828bbaf9f7b288a136dcf96b1cc853d781dfd and re-cloned the repo, and they showed up again. 

Hopefully my latest commit should fix it

**Comment by j-pendlebury** [comment]
This is what I get in the console in Storybook:
image


~~ignore the locale names~~

**Comment by j-pendlebury** [comment]
So there is still an issue in Psammead. 

Seems to be to do with the locales imported in the timestamp containter's storybook file, because removing them fixes the issue, but I'm not sure why

**Comment by dr3** [comment]
> So there is still an issue in Psammead.
> 
> Seems to be to do with the locales imported in the timestamp containter's storybook file, because removing them fixes the issue, but I'm not sure why

It sounds like its something to do with storybook 'rerunning' the moment import. E.g. you load storybook and it runs `moment.defineLocale`, you move around and it reruns `moment.defineLocale` a second time, causing the issue. 

Or maybe even, multiple imports on different stories? Does moving the moment imports to storybook config.js help?

**Comment by j-pendlebury** [comment]
@dr3 no luck with moving those imports to the config file 👎 as far as I'm aware, this story is the only time we import locales, so I have no clue how to fix this

**Review by jroebu14 — APPROVED** [review]

**Review by FK78 — APPROVED** [review]
LGTM!

**Comment by j-pendlebury** [comment]
Will create a separate issue to investigate the Psammead warnings

**Pull request merged**
