### PR TITLE
Radio Schedules - Update Program Card Heading markup and CSS

### LINKED ISSUE #3305: Simplify the DOM structure within Headings in the radio schedule component
**Describe the bug**
We have complicated, nested DOM elements within headings inside the radio schedule programme card.

Heading level 3s are very complex - we should simplify the DOM where possible. Current setup is this:
```
<h3>
  <span role="text">
    <span>NEXT</span>
    <span class="VisuallyHiddenText">,</span>
    <span> جام جهان نما</span>
    <span class="VisuallyHiddenText">, ۱۵:۰۰, </span>
    <span>25/03/2020 GMT</span>
  </span>
</h3>
```

Screenshot 2020-03-25 at 15 02 40

An issue in NVDA that may be related:

When navigating via elements, first it reads `heading level 3/link` + the name of the headline + the start time (whithout the date), but when navigating to the next element, it reads again `heading level 3/link` + just the date. Should it be all announced at once as when navigating via headings/links?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/hausa?renderer_env=live
2. Inspect the radio schedule heading

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #3305

**Overall change:** 
Update Program Card Heading markup and CSS to fix a11y bugs explained in the [issue](https://github.com/bbc/psammead/issues/3305).

**Code changes:**
- Remove `HeadingContentWrapper` as @greenc05 pointed in https://github.com/bbc/psammead/pull/3297#discussion_r401024955
- Replace `display:inline` with `display:inline-block` in the `TitleWrapper` span to fix the a11y bug. These changes require:
  - Apply a `width: 100%` so it stays under the headline
  - Apply the `text-decoration: underline;` when hovering or focus over the Link, otherwise it just underlines the first part of the h3

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] Automated jest tests added (for new features) or updated (for existing features)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by hotinglok — APPROVED** [review]

**Review by OlgaLyubin — APPROVED** [review]
Looks good

**Review by Bopchy — APPROVED** [review]
Looks great 👍 . DOM structure also looks more simple as there are fewer span elements.

**Comment by PriyaKR** [comment]
This can be merged.As per testing by @DenisHdz heading level h3 is read out only once when navigating via the heading/link.
Also a regression looks good to me.

**Comment by DenisHdz** [comment]
> This can be merged.As per testing by @DenisHdz heading level h3 is read out only once when navigating via the heading/link.
> Also a regression looks good to me.

On that note, I'd like to add that thanks to these changes, it is also announced just once when navigating via elements with the arrow keys.

**Pull request merged**
