### PR TITLE
Update psammead snapshots

### LINKED ISSUE #276: Update Psammead snapshots (react-testing-library)
**Is your feature request related to a problem? Please describe.**
After https://github.com/bbc/psammead/issues/273 is complete, the Psammead snapshots should be updated. 

The package.json version numbers will have to be updated. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by jroebu14**
Resolves https://github.com/bbc/psammead/issues/276

**Overall change:** Updates all Psammead's packages to the latest version of `psammead-test-helpers` to make use of new snapshot generator helper that now uses `@testing-library/react`.

**Code changes:**

- any `package.json` files containing `psammead-test-helpers` upgraded to `1.0.1`
- `package-lock.json` files regenerated
- ran `updateSnapshots` script to regenerate snapshot files

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

**Testing notes**
These changes should only affect our test snapshots and nothing user-facing. The risk of regression is low so probably none to minimal testing required.

### CODE REVIEW

**Comment by thekp** [comment]
i think for each package you've updated, you will have to update the respective package.json version and update the changelog. so that it can be republished on NPM.
😭

**Review by thekp — CHANGES_REQUESTED** [review]
~I believe there are 2 missing CHANGELOG updates:~

~psammead-images
psammead-story-promo~ 

**edit**: the files were changed and github did not show the changed files 🙃 


~~

**Comment by jroebu14** [comment]
@thekp whoa good catch!

**Review by thekp — APPROVED** [review]
thanks for the updates, nice work 💯

**Review by dr3 — CHANGES_REQUESTED** [review]
psammead-image needs a changelog, otherwise LGTM

Also this PR has ALLLLL the conflicts

**Review by dr3 — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Comment by PriyaKR** [comment]
Doesn't need a testing from a tester.

**Pull request merged**
