### PR TITLE
Add role of text to brand vis hid text

### LINKED ISSUE #743: IOS brand link splitting
**Describe the bug**
On Safari IOS voiceover the brand link is read out as
```
'BBC news, link, banner, landmark'
'comma, link'
'igbo, link' 
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Use voice over on IOS on safari 
2. Visit stage.bbc.com/igbo
3. hear error

**Expected behaviour**
It reads out `BBC news, Igbo, link, banner, landmark`

**Smartphone (please complete the following information):**

- Device: iPhoneXS
- OS: iOS12.1
- Browser: Safari
- Version: Whatever it comes with

**Additional context**

### PR DESCRIPTION
**Pull request by dr3**
Resolves #743

**Overall change:** Adds `role="text"` to brand to avoid fragmented link reading

**Code changes:**

- Adds `role="text"` to brand visually hidden text

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]
Tested with VoiceOver on iOS with Safari and it reads out correctly `BBC news, Igbo, link, banner, landmark` 👍

**Review by ghost — COMMENTED** [review]
Could we add an assertion to check that the span has the role text.

**Review by j-pendlebury — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by david-boydell** [comment]
This is ready for merge.

**Comment by j-pendlebury** [comment]
@dr3 looks like `psammead-brand` needs to be re-bumped. Also looks like CI is taking a long nap on this PR

**Pull request merged**
