### PR TITLE
bump dependencies to latest

### PR DESCRIPTION
**Pull request by thekp**
Resolves: n/a

**Overall change:** _bumping dependencies in the `package.json`_

**Test notes:** all these tests are dev dependencies, if they pass on CI the changes should be fine.

**I have bumped the following dependencies:**

- [storybook-readme](https://github.com/bbc/psammead/pull/1590)
- [storybook-chromatic](https://github.com/bbc/psammead/pull/1589)
- [@storybook/addon-notes](https://github.com/bbc/psammead/pull/1547)
- [@storybook/addon-viewport](https://github.com/bbc/psammead/pull/1546)
- [@storybook/react](https://github.com/bbc/psammead/pull/1545)
- [gh-pages](https://github.com/bbc/psammead/pull/1544)
- [@storybook/addon-knobs](https://github.com/bbc/psammead/pull/1542)
- [@storybook/addon-actions](https://github.com/bbc/psammead/pull/1539)
- [@testing-library/react](https://github.com/bbc/psammead/pull/1514)
- [@bbc/psammead-assets](https://github.com/bbc/psammead/pull/1480)
- [husky](https://github.com/bbc/psammead/pull/1520)
- [@storybook/theming](https://github.com/bbc/psammead/pull/1540)
- [@storybook/addon-a11y](https://github.com/bbc/psammead/pull/1541)
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by RayNjeri — APPROVED** [review]

**Comment by thekp** [comment]
2 vulnerabilities arise from these dependency bumps

image

**Review by sareh — APPROVED** [review]

**Comment by sareh** [comment]
Approved pending a separate fix for the vulnerabilities that were introduced here.

**Comment by sareh** [comment]
Have opened up a PR to fix the vulnerability in `storybook-readme`: https://github.com/tuchk4/storybook-readme/pull/205 (Noting that pinning to a version without the vulnerability means going from v5.0.6->v3.3.0, so a quick fix forwards would be better in this scenario.)

**Comment by PriyaKR** [comment]
The changes are dev changes by minor bumps doesn't require a testing effort by a tester as long as the tests on CI pass.

**Pull request merged**
