### PR TITLE
Add copyright symbol as a separate prop

### PR DESCRIPTION
**Pull request by EinsteinNjoroge**
Relates to [PR934](https://github.com/bbc/psammead/issues/934) issue

**Context:**
_We need to add a lang attribute to the copyright symbol so that it is always read in English._

**Overall change:** _Separate copyright symbol from copyright text in sitewide links._

**Code changes:**

- _Add `copyrightSymbol` as a separate prop to sitewide links._
- _Bump `psammead-sitewide-links` version to `3.0.0`._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by ghost** [comment]
In what context does the `copyright`symbol change?

**Comment by EinsteinNjoroge** [comment]
@sadickisaac We need to add a `lang` attribute to the copyright symbol so that it is read in English.

**Comment by ghost** [comment]
Will the `copyright` always be read in english?

**Comment by EinsteinNjoroge** [comment]
Yes, based on [this](https://github.com/bbc/psammead/issues/934#issuecomment-513849903) conversation,  the copyright should always be in English.

**Comment by ghost** [comment]
Am mostly concerned with making `copyrightSymbol` a prop. If the `copyright` symbol is not going to change and the `lang` attribute is also not going to change. Do we still need to make that a prop. By us making it a prop, it means it can be changed.

**Comment by EinsteinNjoroge** [comment]
We don't foresee any scenario where `copyright` will be read in any other language

**Comment by EinsteinNjoroge** [comment]
Closing this PR - I'll try a different approach

**Pull request closed without merging**
