### PR TITLE
Fix ProgramCard styling bug in Windows High Contrast Mode

### LINKED ISSUE #3310: Program Card styling bug on IE11 high contrast mode
**Describe the bug**
High contrast mode on Windows 7 with IE11 - you don't see the left side of the border on the 'duration' section at the bottom of the card

Screenshot 2020-03-26 at 15 15 29

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to www.test.bbc.com/hausa?renderer_env=live
2. Scroll down to Radio schedule component (below top stories)
3. See error

**Expected behaviour**

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: Internet Explorer
- Version: 11

**Testing notes**

- [x] This bug fix is expected to need manual testing.

### PR DESCRIPTION
**Pull request by Bopchy**
Resolves #3310

**Overall change:** _Add styling to make backgroundColor of the `ButtonWrapper` transparent when in high contrast mode._

_The side border of the Button disappearing appears to be caused by the `ButtonWrapper`'s backgroundColor somehow covering the border while in high contrast mode. Made `ButtonWrapper` colour transparent in high contrast mode (as opposed to the black (`#222222`) it becomes) so that the border remains visible in all the different high contrast mode themes._

**Before**
Screenshot 2020-03-27 at 19 09 20

**After**
Screenshot 2020-03-30 at 10 32 43

**Code changes:**

- _Add `@media screen and (-ms-high-contrast: active)` styling block to `ButtonWrapper` component._
- _Update snapshots._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by Bopchy** [comment]
Opted to add `outline` styling property as opposed to a `border-left` because border styling adds to the width of the component, and outlines do not.

Added outline to the whole card, as adding it to the button alone 'overrode' the other borders
Screenshot 2020-03-27 at 18 34 52

**Review by DenisHdz — APPROVED** [review]
Thanks for the fix 💯

**Review by itimirichard — APPROVED** [review]
LGTM

**Comment by PriyaKR** [comment]
LGTM.

**Pull request merged**
