### PR TITLE
Define z-index on section-label wrapper

### PR DESCRIPTION
**Pull request by EinsteinNjoroge**
Relates to  https://github.com/bbc/simorgh/pull/5727

**Overall change:** 
_The horizontal bar on the section-label component has a `z-index` of `-1`, this causes it to be hidden behind when the parent component has a `background-color`, this PR adds a `z-index` of `0` to the section-label wrapper to fix this issue._

**Section label inside a div with a white background-color**
Screen Shot 2020-03-02 at 2 32 29 PM

**Section label with `z-index:0` applied to the wrapper**
Screen Shot 2020-03-02 at 3 13 51 PM

**Code changes:**

- _Add `z-index` to the section-label wrapper._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by thekp — APPROVED** [review]
LGTM 👍

**Review by DenisHdz — COMMENTED** [review]
The Section Label Title has a white background-color, which will be seen after applying `GHOST` to the Front Page. I wonder if we should be looking at removing it and hide the line over it in a different way than using the color trick, which might not involve using the `z-index: -1` and therefore not adding this `z-index: 0` to the wrapper.

**Comment by EinsteinNjoroge** [comment]
> The Section Label Title has a white background-color, which will be seen after applying `GHOST` to the Front Page. I wonder if we should be looking at removing it and hide the line over it in a different way than using the color trick, which might not involve using the `z-index: -1` and therefore not adding this `z-index: 0` to the wrapper.

@DenisHdz in [this PR](https://github.com/bbc/psammead/pull/3133) the background-color was changed to GHOST.

**Comment by DenisHdz** [comment]
> > The Section Label Title has a white background-color, which will be seen after applying `GHOST` to the Front Page. I wonder if we should be looking at removing it and hide the line over it in a different way than using the color trick, which might not involve using the `z-index: -1` and therefore not adding this `z-index: 0` to the wrapper.
> 
> @DenisHdz in [this PR](https://github.com/bbc/psammead/pull/3133) the background-color was changed to GHOST.

Awesome, I had looked at it on the Live sites which don't have this version yet 👍

**Review by DenisHdz — APPROVED** [review]

**Review by Bopchy — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me.
Screen Shot 2020-03-02 at 14 31 29

**Pull request merged**
