### PR TITLE
Make linking section labels work on IE11

### PR DESCRIPTION
**Pull request by andrew-nowak**
~~THIS WILL GET BLOCKED BEHIND `@bbc/psammead-section-label@2.3.4` - 2.3.4 isn't ready to be pulled into Simorgh (requires more work on `@bbc/psammead-story-promo`) - possibly requires reverting #1829, merging this, then unreverting #1829? Will discuss next week~~
Revert was done

Resolves #my nightmares

This is blocking bbc/simorgh#3266 from going live

**Overall change:** The previous work to enable linking section labels encountered a bug in IE11's implementation of flexbox

**Code changes:**

- This https://github.com/philipwalton/flexbugs#flexbug-3

Suggestions for better names for `FlexContainerContainer` gratefully received.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Works great in ie11.

**Review by DenisHdz — CHANGES_REQUESTED** [review]
Could `FlexContainerContainer` be called `FlexContainerWrapper` instead?

**Review by DenisHdz — APPROVED** [review]

**Review by dr3 — APPROVED** [review]
Very strange, does the job and linked to where found though, lgtm

**Pull request merged**
