### PR TITLE
Bumping dependency

### PR DESCRIPTION
**Pull request by thekp**
Resolves n/a

**Overall change:** bumping dependencies

testing notes: you don't have to test dev dependencies

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — APPROVED** [review]

**Review by RayNjeri — CHANGES_REQUESTED** [review]
Shouldn't https://github.com/bbc/psammead/blob/7a444982dcaafc080df82b9cec162c2caabe708d/package.json#L46 also be bumped to `2.0.1`?

**Comment by thekp** [comment]
https://github.com/bbc/psammead/pull/1592/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L46

@RayNjeri  i'll include it a part of this PR, as it is for the core psammead package.json

**Review by RayNjeri — APPROVED** [review]
LGTM

**Comment by PriyaKR** [comment]
LGTM.

These are the components Psammead brand, consent banner, copyright, image placeholder, inline link,media indictor, section label,sitewidelinks,timestamp,locales for which the below utilities are bumped and looks good.
gel-foundations": , 3.0.3 - 3.2.0"
psammead-styles": 1.2.0 - 2.0.1
psammead-visually-hidden-text 1.0.7 - 1.1.1

**Pull request merged**
