### PR TITLE
fix a11y comma bug in psammead-navigation

### LINKED ISSUE #9616: Resolve Talkback reading comma in a range of components in Simorgh and Psammead
**Describe the bug**
TalkBack is reading comma in some of our psammead components.

**To Reproduce**
Steps to reproduce the behaviour:

1. Use TalkBack in the following page: https://www.bbc.com/mundo
2. Navigate to the top brand 
3. Single item swipe on the brand link
4. Notice that the comma gets read out.

**Expected behaviour**
Should not read out comma in the following components:

In Psammead psammead-brand component
Psammead CurrentLink in psammead-navigation

**Smartphone (please complete the following information):**

- Device: Samsung A5 2017
- OS: Android 8.0.0
- Browser chrome
- Version 95.0.4638.50

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
Brand component is the following:
Screenshot 2021-11-01 at 11 47 50

Only test available is on storybook generated bt the PR

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves [#9561](https://github.com/bbc/simorgh/issues/9616)

Concatenated comma to the text.

**Code changes:**
- As Above

---

- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)
- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by nicola-d-bbc — APPROVED** [review]

**Review by MuhammadAHussain — APPROVED** [review]
LGTM 👍

**Comment by DarioR01** [comment]
Works on Talkback
Test link: https://5d28eb5ee163f6002046d6fb-kokqnwbbod.chromatic.com/?path=/story/components-navigation-canonical--igbo

**Comment by greenc05** [comment]
Thanks @DarioR01 Please confirm it is as expected will all our supported screen readers.

**Comment by DarioR01** [comment]
Checked with no CSS and shows content as intended

**Comment by DarioR01** [comment]
Test Link: https://5d28eb5ee163f6002046d6fb-kokqnwbbod.chromatic.com/?path=/story/components-navigation-canonical--igbo
Need test on:

- [ ] JAWS
- [x] TalkBack Dario
- [x] NVDA Dario
- [x] VoiceOver MAC Dario
- [x] VoiceOver iPhone Pedram

**Review by pvaliani — APPROVED** [review]
working on iPhone Vo

**Comment by paruchurisilpa** [comment]
Test Link: https://5d28eb5ee163f6002046d6fb-kokqnwbbod.chromatic.com/?path=/story/components-navigation-canonical--igbo

- [x] JAWS

Checked JAWS and works as expected..

**Pull request merged**
