### PR TITLE
Adding padding between audio player and footer

### LINKED ISSUE #3111: No padding between the live radio audio player and the footer
**Describe the bug**
There is currently no padding between the audio player and the footer.

**To Reproduce**

See https://www.bbc.com/tamil/bbc_tamil_radio/liveradio for an example

**Expected behaviour**
1008 -> 32px
1007 and below -> 16px

Designs: https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5df76934d852e81aee9c21ea

**Screenshots**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

### PR DESCRIPTION
**Pull request by rebeccamcginn**
Resolves https://github.com/bbc/psammead/issues/3111

**Overall change:** 
Added 32px margin for 1008 and above, 16px margin for 1007 and below

**Code changes:**
Added media query for margin padding

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]
Needs version and changelog update :)

**Review by ryanmccombe — APPROVED** [review]

**Review by RichardPK — APPROVED** [review]
LGTM. Beautiful use of the GEL consts.

**Review by RichardPK — DISMISSED** [review]
Just noticed the design [referenced in the issue](https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5df76934d852e81aee9c21ea) is for OD radio, while the [example of the problem](https://www.bbc.com/tamil/bbc_tamil_radio/liveradio) is a live radio site. No doubt a change is still necessary, just thought it was worth flagging that the values could be different. The [live radio design](https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5dbc64397b5ffe22b0383dd5) spacing looks slightly different to OD radio: 

Screenshot 2020-02-11 at 17 00 15

Screenshot 2020-02-11 at 17 08 09

**Comment by rebeccamcginn** [comment]
> Just noticed the design [referenced in the issue](https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5df76934d852e81aee9c21ea) is for OD radio, while the [example of the problem](https://www.bbc.com/tamil/bbc_tamil_radio/liveradio) is a live radio site. No doubt a change is still necessary, just thought it was worth flagging that the values could be different. The [live radio design](https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5dbc64397b5ffe22b0383dd5) spacing looks slightly different to OD radio:
> 
> Screenshot 2020-02-11 at 17 00 15
> 
> Screenshot 2020-02-11 at 17 08 09

The values were approved by Ed

**Comment by rebeccamcginn** [comment]
> Just noticed the design [referenced in the issue](https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5df76934d852e81aee9c21ea) is for OD radio, while the [example of the problem](https://www.bbc.com/tamil/bbc_tamil_radio/liveradio) is a live radio site. No doubt a change is still necessary, just thought it was worth flagging that the values could be different. The [live radio design](https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5dbc64397b5ffe22b0383dd5) spacing looks slightly different to OD radio:
> 
> Screenshot 2020-02-11 at 17 00 15
> 
> Screenshot 2020-02-11 at 17 08 09

**Review by karinathomasbbc — APPROVED** [review]

**Pull request merged**
