### PR TITLE
Give Navigation a max-width of 80rem

### LINKED ISSUE #708: Navigation should have a max-width of 80rem
**Describe the bug**
Following https://github.com/bbc/psammead/issues/645, the Navigation should also have a max-width of 80rem.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://bbc.github.io/psammead/iframe.html?id=components-navigation--igbo-with-brand
2. See how Navigation isn't limited to 1280px

**Expected behaviour**
The Navigation is inside a 1280px wide wrap, to avoid it going all the way to the left of the screen at widths over 1280px.

**Screenshots**
nav-fail

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #708

**Overall change:**
Update Navigation to have a max-width of 80rem.

**Code changes:**
- Add a wrapper within the `StyledNav` with a max-width of 80rem.
- Tweak `SkipLink` to match with the brand.
- Use the brand with a link in the igbo story.
- Update snapshots.

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — CHANGES_REQUESTED** [review]
Looks great, can you please bump psammead brand in this package so they both drop to the smaller margin at the same time please? Brand is on 4.1.2 now. After that, 👍

**Review by dr3 — APPROVED** [review]
👍 LGTM

**Review by j-pendlebury — APPROVED** [review]
Looks good 👍

**Comment by david-boydell** [comment]
Looks good, this is ready for merge

**Pull request merged**
